### ISSUE TITLE
onCancelled not firing

### ISSUE THREAD

**Issue by alexgarrett** [braintree/braintree-web#89] opened 2015-10-23 10:23 UTC
I saw another issue (https://github.com/braintree/braintree-web/issues/71) relating to this. I'm using 2.15.1 and I'm not seeing onCancelled fire at all.

```js
braintree.setup(codecourse.braintree_client_token, 'paypal', {
    container: 'bt-paypal',

    onCancelled: function () {
        // nothing fired here
    },

    onPaymentMethodReceived: function () {
        // this is fine
    }
});
```

**Comment by kyledetella** [comment] 2015-10-23 15:38
@alexgarrett it looks like you are correct. Thanks for bringing this up, we will work on getting a fix out. In the meantime, you should be able to use version `2.14.2`.

**Comment by alexgarrett** [comment] 2015-10-23 16:41
Thanks for the quick reply @kyledetella, `2.14.2` is working perfectly.

**Comment by kyledetella** [comment] 2015-10-23 21:20
@vijaykumar-krishnaswamy, a fix for `onCancelled` has been deployed as a hotlink to `[https://js.braintreegateway.com/v2/braintree.js](https://js.braintreegateway.com/v2/braintree.js)`. We will update `npm` and this repo accordingly with a `2.15.2` patch on Monday.

I'll leave this issue open until we have deployed that.

**Comment by kyledetella** [comment] 2015-10-26 15:10
This has been fixed with the [`2.15.2`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2152) release.

**Closed by kyledetella** 2015-10-26 15:10 UTC
Labels: bug, PayPal

**Comment by alexgarrett** [comment] 2015-10-26 15:14
Thanks so much :+1:

**Comment by csm123** [comment] 2015-11-27 19:53
I'm experiencing this issue with the latest version using a custom implementation.

```javascript
braintree.setup(clientToken, "custom", {
            id: "braintree-hosted-fields-form",
            hostedFields: {
              number: {
                selector: "#card-number"
              },
              cvv: {
                selector: "#cvv"
              },
              expirationDate: {
                selector: "#expiration-date"
              }
              }
            },
            paypal: {
              container: "braintree-hosted-fields-form-paypal",
              onCancelled: function() {
                alert('cancelled');
              }
            },
          });
```

`onCancelled` does not fire when the user closes the PayPal window before completing the flow. I do not experience this with a PayPal-only implementation, only a custom one with PayPal.

**Comment by EvanHahn** [comment] 2015-11-30 17:51
@csm123 The PayPal `onCancelled` callback is fired when the user goes through the whole flow and clicks "Cancel", as shown below:

![screenshot](https://cloud.githubusercontent.com/assets/777712/11479612/ee8ca91a-9760-11e5-863c-d6caac736e47.png)

It's not fired when the user closes the PayPal window.

Does this help?

**Comment by dganoff** [comment] 2016-03-10 20:58
This regression seems to have returned for me in version 2.21.0.

**Comment by lilaconlee** [comment] 2016-03-14 14:51
@dganoff So far, we've been unable to recreate this issue. Could we get some more information about your integration to help you debug this? If you don't want to share your integration publicly, feel free to contact our support team at support@braintreepayments.com.

**Comment by Sartoric** [comment] 2016-03-25 15:42
Same issue here using last version.
Please find the following simple test I'm running

```
<?php
 error_reporting(E_ALL);
 ini_set('display_errors', '1');

require_once 'class/braintree/lib/Braintree.php';

Braintree\Configuration::environment('sandbox');
Braintree\Configuration::merchantId('<SOMETHING>');
Braintree\Configuration::publicKey('<SOMETHING>');
Braintree\Configuration::privateKey('<SOMETHING>');

$user=array();

$user['id']='id1';
$user['name']='test';

try {
  $customerobj = Braintree\Customer::find($user['id']);
} catch (Braintree_Exception_NotFound $e) {
  $result = Braintree\Customer::create([
      'id' => 'asdfghjkloiuytrewqasderftgcvfrtyhujikolpbdsa', // failed creation test
      //'id' => $user['id'],
      'firstName' => $user['name']
  ]);  
  if ($result->success){
      $customerobj->$result->customer;
  }
  else {
    $customerobj=null;
    foreach($result->errors->deepAll() AS $error) {
        echo($error->code . ": " . $error->message . "\n");
    }
  }
}

if ($customerobj){
  $customerid = $customerobj->id ;
  $clientToken = Braintree\ClientToken::generate([
      "customerId" => $customerid
  ]);
}
else {
  ?><h1> Error </h1><?php
  exit;
}
?>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Braintree Checkout Test</title>
  </head>
  <body>

  <form id="myform" method="post" action="test_brain_server.php">
    <div id="paypal-container"></div>
    <input type='hidden' id="payment_method_nonce" name="payment_method_nonce">
  </form>

  <script src="https://js.braintreegateway.com/js/braintree-2.21.0.min.js"></script>

<script type="text/javascript">
  braintree.setup("<?=$clientToken?>", "custom", {
    paypal: {
      container: "paypal-container",
    },
    onError: function(obj){
      console.log('Error');
      console.log(obj);
    },
    onCancelled: function(obj){
      alert('cancel');
      console.log('Cancel');
      console.log(obj);
    },    
    onPaymentMethodReceived: function (obj) {
      console.log('Received');
      console.log(obj);
      document.getElementById('payment_method_nonce').value = obj.nonce;
      document.getElementById('myform').submit();     
    },
    onAuthorizationDismissed: function(obj){
      console.log('Dismissed');
      console.log(obj);      
    }
  });
</script>
  </body>
</html>
```

**Comment by EvanHahn** [comment] 2016-03-25 17:36
@Sartoric It looks like you've specified `onCancelled` as a top-level option but it needs to be nested under the `paypal` object. Something like this should do it in your case:

```js
braintree.setup("<?=$clientToken?>", "custom", {
  paypal: {
    container: "paypal-container",
    onCancelled: function(obj){
      // ...
    }
  },
  // ...
});
```

(The same is true for `onAuthorizationDismissed`, by the way—I noticed that was specified at the top level but also needs to be moved under `paypal`.)

Let us know if this helps!

**Comment by Sartoric** [comment] 2016-03-25 17:51
Yep, right. Thanks for you feedback .
I copy pasted the onPaymentMethodReceived and I didn't noticed it wasn't correctly nested.
