### ISSUE TITLE
sjcl.js Module not found: Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by JezNorton** [braintree/braintree-web#368] opened 2018-05-15 13:43 UTC
### General information

* SDK version: 3.33.0 
* Environment: Sandbox
* Browser and OS: Chrome 66.0.3359.170 (64-bit) on Windows 10 1709 
* Angular:  5.2.10
* Node: 10.1.0
* Angular CLI: 6.0.1
### Issue description

On ng build the following error appears: WARNING in ./node_modules/braintree-web/data-collector/vendor/sjcl.js
Module not found: Error: Can't resolve 'crypto' 
Following error in console when trying to call hosted fields:

ERROR Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at Object../node_modules/braintree-web/lib/promise.js (vendor.js:117848)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/american-express/american-express.js (vendor.js:110049)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/american-express/index.js (vendor.js:110234)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/index.js (vendor.js:115971)
    at __webpack_require__ (bootstrap:81)
    at new BraintreeComponent (braintree.component.ts:26)
    at createClass (vendor.js:65560)
    at Object../node_modules/braintree-web/lib/promise.js (vendor.js:117848)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/american-express/american-express.js (vendor.js:110049)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/american-express/index.js (vendor.js:110234)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/braintree-web/index.js (vendor.js:115971)
    at __webpack_require__ (bootstrap:81)
    at new BraintreeComponent (braintree.component.ts:26)
    at createClass (vendor.js:65560)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (vendor.js:57830)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
defaultErrorLogger @ vendor.js:54528
push../node_modules/@angular/core/esm5/core.js.ErrorHandler.handleError @ vendor.js:54589
next @ vendor.js:58587
schedulerFn @ vendor.js:57421
push../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:159422
push../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ vendor.js:159369
push../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._next @ vendor.js:159310
push../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.next @ vendor.js:159274
push../node_modules/rxjs/_esm5/Subject.js.Subject.next @ vendor.js:158994
push../node_modules/@angular/core/esm5/core.js.EventEmitter.emit @ vendor.js:57401
(anonymous) @ vendor.js:57861
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/esm5/core.js.NgZone.runOutsideAngular @ vendor.js:57787
onHandleError @ vendor.js:57861
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:392
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:677
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
(anonymous) @ vendor.js:82367
push../node_modules/rxjs/_esm5/Observable.js.Observable._trySubscribe @ vendor.js:158524
push../node_modules/rxjs/_esm5/Observable.js.Observable.subscribe @ vendor.js:158512
push../node_modules/rxjs/_esm5/operators/map.js.MapOperator.call @ vendor.js:168103
push../node_modules/rxjs/_esm5/Observable.js.Observable.subscribe @ vendor.js:158509
push../src/app/login/login.component.ts.LoginComponent.login @ login.component.ts:35
(anonymous) @ LoginComponent.html:13
handleEvent @ vendor.js:66668
callWithDebugContext @ vendor.js:68177
debugHandleEvent @ vendor.js:67764
dispatchEvent @ vendor.js:63083
(anonymous) @ vendor.js:65422
schedulerFn @ vendor.js:57433
push../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:159422
push../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ vendor.js:159369
push../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._next @ vendor.js:159310
push../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.next @ vendor.js:159274
push../node_modules/rxjs/_esm5/Subject.js.Subject.next @ vendor.js:158994
push../node_modules/@angular/core/esm5/core.js.EventEmitter.emit @ vendor.js:57401
push../node_modules/@angular/forms/esm5/forms.js.NgForm.onSubmit @ vendor.js:78270
(anonymous) @ LoginComponent.html:12
handleEvent @ vendor.js:66668
callWithDebugContext @ vendor.js:68177
debugHandleEvent @ vendor.js:67764
dispatchEvent @ vendor.js:63083
(anonymous) @ vendor.js:63708
(anonymous) @ vendor.js:87855
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ vendor.js:57830
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

**Comment by crookedneighbor** [comment] 2018-05-15 14:15
Closing as a duplicate of https://github.com/braintree/braintree-web/issues/366

**Closed by crookedneighbor** 2018-05-15 14:15 UTC

**Comment by crookedneighbor** [comment] 2018-05-15 14:16
Copied comment from #366 

> From what I can tell, looking at the [Stanford JavaScript Crypto Library](https://github.com/bitwiseshiftleft/sjcl), requiring the [crypto module](https://github.com/bitwiseshiftleft/sjcl/blob/00bd42dae9ebc3a28708db2053ffa2e88f99ad1e/core/random.js#L483-L490) is done in such a way that if it fails to require it, it falls back to the browser's implementation. 

> I'm going to close this for now, but feel free to [open an issue on sjcl](https://github.com/bitwiseshiftleft/sjcl/issues) and we'll update our vendored sjcl library if they make an adjustment for Angular v6.

**Comment by crookedneighbor** [comment] 2018-08-09 20:44
A fix for this has been released with 3.36.0

See https://github.com/braintree/braintree-web/issues/366#issuecomment-411858050
