### ISSUE TITLE
Issue with tabbed navigation

### ISSUE THREAD

**Issue by clupprich** [braintree/braintree-web#62] opened 2015-08-10 11:27 UTC
We are using braintree.js (custom integration) and are running into the following problem:

We are using a tabbed layout for the CC parts and Paypal part. So clickes on a PayPal icon and sees the Paypal button to login or he clicks on a CC symbol and sees the CC fields like number, expiration date,... 

Now, when a user has entered both details (logged into Paypal and filled out all CC fields) of course we're running into a problem, because the form only has a single `payment_method_nonce` field. I tried to fix that by remembering the nonce in a data attribute on the payment method containers and setting it dynamically based on what payment method is selected, but that doesn't work - probably because the payment method nonce is the same for both payment methods.

Can you think of any hack how to work around our problem?

**Comment by ms7s** [comment] 2015-08-10 12:34
@clupprich have you seen the comments for issue #29? Maybe one of the hacks mentioned there would be useful for you as well.

**Comment by EvanHahn** [comment] 2015-08-11 17:03
Custom integrations do their best to figure out which payment method a user wants, so what you're seeing is intended behavior. A couple of us looked at this issue and had a couple of workarounds:

1. Prevent your users from going back to the credit card tab if they've already logged in with PayPal. If they cancel PayPal, then the user can switch tabs again.

   Here's a bit of sample code that might help:

   ```javascript
   // This is a "fake" function that is called when tabs are switched.
   function switchTabs(switchTo) {
     // Don't switch tabs if we already have a nonce.
     var alreadyHasNonce = !!$('input[name="payment_method_nonce"]').val();
     if (alreadyHasNonce) {
       return;
     }

     // Continue switching tabs...
     // ...
   }

   // ...

   braintree.setup('YOUR_TOKEN', 'custom', {
     // ...
     paypal: {
       container: 'your-paypal-container',
       onCancelled: function () {
         // Clear the nonce if PayPal has been canceled.
         $('input[name="payment_method_nonce"]').val('');
       }
     }
   });
   ```

2. If you're looking to have very tight control over your Braintree integration, you can use [direct tokenization](https://developers.braintreepayments.com/javascript+ruby/guides/credit-cards#tokenize-card). When doing this, take care to never send card data to your server (removing the `name` attribute from sensitive inputs usually solves this). This is a little more code, but we're happy to send an example if this sounds interesting.

For what it's worth, this is a problem we are currently investigating.

Hope this helps!

**Comment by clupprich** [comment] 2015-08-11 17:21
Hej @EvanHahn! Thanks for getting back to me! We've in fact tried method 1 (disabling CC) yesterday and that's what we will go for for now. Option 2 is probably even better, but will take us a bit more time and QA to get done right and tested. Thanks for the great response (as always)! :)

**Comment by EvanHahn** [comment] 2015-08-11 18:27
Glad we could help. I'm going to close this issue for now but feel free to reach out again if needed!

**Closed by EvanHahn** 2015-08-11 18:27 UTC
