### ISSUE TITLE
Safari keyboard always shows up on mobile

### ISSUE THREAD

**Issue by Mocha--** [braintree/braintree-web#250] opened 2017-01-20 05:30 UTC
Hi,

I am experiencing a weird bug in hosted fields that not only happens on my site, but also happens on the examples of hosted fields, one of which is http://codepen.io/braintree/pen/mPgdPN. 

To reproduce it:
1. Go to http://codepen.io/braintree/pen/mPgdPN with safari on mobile.
2. Fill all fields with valid values.
3. Focus on any of those fields, after which the keyboard should show up.(Please do not click 'done' or other buttons to close the keyboard, keep it up)
4. Click the pay button on the demo to submit payment.(At the meanwhile, the keyboard should keep open)
5. Click any empty space, the keyboard will always show up.

I think this is because one of the fields is still under focus. But this is really annoying and I do not have a solution to this problem.

Hope anyone could provide any suggestion.

Thanks,

**Comment by skunkworks** [comment] 2017-01-23 19:02
@Mocha-- Thanks for opening this issue. My first impression is that this is Mobile Safari doing something strange. We'll take a look and see what we can do.

**Comment by crookedneighbor** [comment] 2017-02-01 22:06
Closing this as a duplicate of https://github.com/braintree/braintree-web/issues/137

**Closed by crookedneighbor** 2017-02-01 22:06 UTC
Labels: Hosted Fields

**Comment by skunkworks** [comment] 2017-02-01 22:30
After some investigation, we've determined that Mobile Safari has buggy behavior when `input` elements are inside iframes (as is the case with Hosted Fields): the `blur` event of the input does not fire reliably when the field iframe loses focus. This leaves the page in an indeterminate state where it thinks the input still has focus, so it displays the keyboard. This is similar behavior to what was reported in https://github.com/braintree/braintree-web/issues/137.

We aren't able to fix the keyboard issue, but one possible workaround is to create a "dummy" `input` element on your page, then focus & blur it when the payment button is tapped:

```html
<input id="dummyInput" style="position: absolute; left: -5000%; top: -5000%;">
```

```javascript
$('#cardForm').submit(function (event) {
    event.preventDefault();

    $('#dummyInput').focus();
    $('#dummyInput').blur();

    hostedFieldsInstance.tokenize(function (err, payload) {
        if (err) {
            console.error(err);
            return;
        }

        // This is where you would submit payload.nonce to your server
        alert('Submit your nonce to your server here!');
    });
});
```
