### ISSUE TITLE
Minified main script

### ISSUE THREAD

**Issue by alexhancock** [braintree/braintree-web#85] opened 2015-10-16 00:49 UTC
Is it necessary to have the built file in `dist` be pre-minified? For what it's worth, it causes a warning when requiring this module via webpack, which I am sure quite a few folks are doing.

![screen shot 2015-10-15 at 5 43 10 pm](https://cloud.githubusercontent.com/assets/427516/10531236/3cd0eed6-7364-11e5-9748-cf0e50d06cae.png)

I don't know if it is a huge issue for others, but it might be nice to have the package's main script not be minified.

One solution could be to include a `braintree.js`, and a `braintree.min.js` in `dist`. This way those who want to have a pre-minified version they could require for convenience won't be too bothered.

My guess though, is that most people using npm modules on the web have something like webpack or browserify set up, and likely already have minification as part of their build process.

Just a thought - Cheers!

**Comment by mrak** [comment] 2015-10-16 16:46
Possible duplicate of #1 and #52?

**Comment by kyledetella** [comment] 2015-10-19 13:22
@alexhancock I do agree with your sentiment that developers consuming our library via `npm` will have build chains of their own and as was mentioned in #1 we may at one point in the future ship an unminified version here, but that is not in our immediate plans.

As for your particular use case with Webpack,I am going to close this since it is a duplicate of #52 as @mrak mentioned. [This comment](https://github.com/braintree/braintree-web/issues/52#issuecomment-119237298) may be of particular interest.

Thanks for bringing this matter up. Given the rise of Webpack's popularity, we will make considerations for it as we iterate on future tooling and release strategies.

**Closed by kyledetella** 2015-10-19 13:22 UTC
Labels: duplicate
