### ISSUE TITLE
Expiration year after 2040 marked as invalid

### ISSUE THREAD

**Issue by bking-bread** [braintree/braintree-web#575] opened 2021-06-24 18:55 UTC
### General information

* SDK version: 3.76.0
* Environment: Sandbox (and I suspect Production as well)
* Browser and OS:  All

### Issue description

When testing our Braintree form in our application our QA team found that entering an expiration year bigger than 2040 it was triggering our validation error message. As this is most likely an extreme edge case its not urgent for resolution. I did some poking around on your examples page and found that it happens there as well (https://developer.paypal.com/braintree/docs/guides/hosted-fields/examples) I'm not sure if there is a valid reason for why a year after 2040 would be considered invalid, so if there is please let me know.

**Comment by crookedneighbor** [comment] 2021-06-24 19:09
We made the decision to set the max year for expiration dates in the future to be 19 years. We did this to follow PayPal's assumptions in their UI that cards can expire at most in 19 years in the future. In practice, card issuers typically only set expiration years for a few years out, but there's nothing guaranteeing thought. We though in practice, setting a max range of 19 years out was safe for catching any outliers.

Do you have an example from a card issuer where cards more than 19 years in the future _would_ be valid? The only place I've seen do more than 19 years is Amazon, which does 20 years. But again, I believe that's done out of an abundance of caution, not because there are actually cards out in the wild expiring in 20 years.

**Comment by crookedneighbor** [comment] 2021-06-25 20:51
This is working as intended, so I'm going to close this issue, but if you have a use case where you'd need expiration year to be extended beyond the 19 year threshold, please comment here with the details.

**Closed by crookedneighbor** 2021-06-25 20:51 UTC
