### ISSUE TITLE
onReady is not getting triggered

### ISSUE THREAD

**Issue by PrinalKhandelwal** [braintree/braintree-web#162] opened 2016-05-04 18:44 UTC
I am writting a automation testcase for generating a nonce using phantomjs for PayPal braintree custom setup. 
I am using phantomjs version 2.1.1 and braintree javascript version 2.23.0 but not getting any response on onReady function called. I was wondering if you could guide me. Below is my program

```js
var page = require('webpage').create();
var system = require('system');
var checkout;

page.open("about:blank", function(status) {
	if (status === "success") {
		console.log("Page loaded successfully");

		var script = document.createElement("script");
		script.setAttribute("type", "text/javascript");
		script.setAttribute("charset", "utf-8");

		var paymentDiv = document.createElement("div");
		paymentDiv.id = "paypal-container";
		document.body.appendChild(paymentDiv);

		script.onload = function() {	
 			console.log("On load called");
			var client = new braintree.setup("client-token", "custom",
				{
					onReady: function(integration) {
					    console.log("onReady got called...");
						checkout = integration;
						checkout.paypal.initAuthFlow();
						},
					paypal: {
						container: "paypal-container",
						singleUse: true,
						amount: 10.00,
						currency: 'USD',
						locale: 'en_us',
						enableShippingAddress: true,
						headless: true
					},			
					onPaymentMethodReceived: function(payload) {
						// retrieve nonce from payload.nonce
						console.log("The nonce is:");
						console.log(payload.nonce);
						phantom.exit();
					}
				}
			);
			console.log('end of onLoad');
		};
		script.src = 'https://js.braintreegateway.com/js/braintree-2.23.0.min.js'; 
     	document.getElementsByTagName('head')[0].appendChild(script);	
	} 
});
```

**Comment by mrak** [comment] 2016-05-04 21:47
Are you getting any errors aside from `onReady` silently never being called?
Does `end of onLoad` successfully log to the console?

**Comment by crookedneighbor** [comment] 2016-05-04 21:49
@PrinalKhandelwal I've updated your issue to include backticks for code formatting.

**Comment by PrinalKhandelwal** [comment] 2016-05-04 21:50
Yes, end of onLoad is getting called.

**Comment by mrak** [comment] 2016-05-04 21:53
If you add `onError` to your setup, does it report any errors?

**Comment by PrinalKhandelwal** [comment] 2016-05-04 22:09
No

**Comment by mrak** [comment] 2016-05-04 22:30
Is it only in automated testing environments that `onReady` fails to fire?

**Comment by PrinalKhandelwal** [comment] 2016-05-04 22:45
It is not responding when I am trying to call using phantomjs for my backend API testing. I am using the 2.1.1 phantomjs version.
For front end testing it works fine.

**Comment by mrak** [comment] 2016-05-05 16:18
Since front-end testing appears to work as intended, it may be a testing setup or phantomjs issue.

Give our excellent support team a ring at support@braintreepayments.com

I'll follow up with them about this GitHub issue as well.

**Comment by dfibuch** [comment] 2016-05-19 11:34
I am also having an issue with getting onReady to return me back anything. It seems to be triggering but the object that is returned is undefined. I am using the braintree-angular library to do this, but that just does a simple "braintree.setup(token, 'dropin', options);" so seems like it's all been correctly setup.

**Comment by mrak** [comment] 2016-05-19 17:29
What do you have in your `options`?

**Comment by dfibuch** [comment] 2016-05-20 10:29
Found what the issue is - its a problem within braintree-angular.js library where the scope seems to change when the code is called to setup the integration.

So my issue is not related to this ticket, sorry for the misdirection.

**Comment by mrak** [comment] 2016-05-20 19:07
Glad you found the problem!

I'll close this issue in the meantime. If additional `onError` problems come up a new ticket can be opened.

**Closed by mrak** 2016-05-20 19:07 UTC
