### ISSUE TITLE
DropIn setup does not automatically show the default user credit card

### ISSUE THREAD

**Issue by ppcano** [braintree/braintree-web#76] opened 2015-09-25 11:11 UTC
When the user has multiple credit cards and the `default` one is changed via the API, the next time that the `dropIn` menu is shown, the new default card is not shown as main card to proceed with the payment.

**Comment by kyledetella** [comment] 2015-09-25 13:06
@ppcano I am going to close this as a duplicate issue. See #5 and further discussion on [this thread](https://github.com/braintree/braintree_android/issues/23).

**Closed by kyledetella** 2015-09-25 13:06 UTC
Labels: duplicate

**Comment by crookedneighbor** [comment] 2016-09-01 18:05
Drop-In now has a boolean parameter you can pass in called `defaultFirst`

> When you specify a customerID that has vaulted payment methods associated with it, Drop-in displays a list of those payment methods and automatically pre-selects the one used most recently. If you pass defaultFirst, Drop-in will instead pre-select the payment method marked as default for the customer. 

The docs for this are the last entry in [this table](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/configuration#setup-method-options)

**Comment by hariharasudhankm** [comment] 2016-09-03 06:15
Hey @crookedneighbor i've tried your method, but the dropin still shows the first add card info only.

**Comment by EvanHahn** [comment] 2016-09-09 17:16
@hariharasudhankm What do you mean by "first add card info"?

Also, could you make sure you're on the latest Braintree.js version? You can check the version in your JavaScript console by typing `braintree.VERSION`. The `defaultFirst` feature [was added in version 2.24.0](https://github.com/braintree/braintree-web/blob/2.x/CHANGELOG.md#2240) and the current version is 2.28.0.

**Comment by zedtux** [comment] 2017-11-04 19:16
@EvanHahn I'm facing the issue that `defaultFirst` is not available as my version of Braintree.js is `2.15.7` but I'm loading Braintree.js from https://js.braintreegateway.com/v2/braintree.js.

Why is the Braintree.js version so old on the braintree servers?

**Comment by crookedneighbor** [comment] 2017-11-06 14:17
@zedtux We made the decision a while ago to stop putting the latest v2 version on the hotlink url you are using. The hotlinking model made it difficult to maintain a stable product, since all merchant checkouts were immediately and simultaneously affected by any regressions in the code. 

You should be able to swap out https://js.braintreegateway.com/v2/braintree.js for https://js.braintreegateway.com/js/braintree-2.32.1.min.js and be good to go.

**Comment by zedtux** [comment] 2017-11-07 08:07
Oh, okay. That's kind of bad as all blog articles are mentioning https://js.braintreegateway.com/v2/braintree.js ...

But okay, thank you very much @crookedneighbor for the information, I will use that!
