### ISSUE TITLE
Expected intent=tokenize to be passed to SDK, but got intent=capture

### ISSUE THREAD

**Issue by ninosaurus** [braintree/braintree-web#544] opened 2020-12-08 12:58 UTC
### General information

* SDK version: 3.69.0
* Environment: Sandbox
* Browser and OS: Google Chrome | 86.0.4240.198 (Official Build) (x86_64) on MacOS 11.0.1

### Issue description

> We are trying to move to the latest braintree-web SDK and we encounter some questions regarding error messages with Paypal Checkout. We are using a billing agreement (with saving payment method to Braintree user) and with the received token we authorize payment on the server-side.

This is our old code for braintree-web@2.32.1
```jsx
  braintree.setup(braintreeClient, 'custom', {
    paypal: {
      singleUse: false,
      currency: 'USD',
      locale: 'en_us',
      enableShippingAddress: true,
      headless: true
    },
    dataCollector: {
      kount: { environment },
      paypal: true
    },
    onPaymentMethodReceived: (paymentMethod) => {
      this.payWithNewPayPal(paymentMethod);
    },
    onReady: (payPalIntegration) => {
      setPayPalIntegration(payPalIntegration);
    }
  });
```

New code with latest braintree-web version typed in React
```jsx
   const [isPaypalLoaded, setIsPaypalLoaded] = useState(false);

   useEffect(() => {
    if (clientInstance !== null) {
      PaypalCheckout.create({
        client: clientInstance
      })
        .then((paypalCheckoutInstance) => {
          paypalCheckoutInstance.loadPayPalSDK({
            vault: true
          })
         .then(() => {
            window.PayPalButton = window.paypal.Buttons.driver('react', {
              React,
              ReactDOM
            });
            setIsPaypalLoaded(true);
         });
      });
    }, [clientInstance]);

  if (!isPaypalLoaded) {
    return null;
  }

  const { PayPalButton } = window;
  return (
    <PayPalButton
      style={PAYPAL_BUTTON_STYLE}
      fundingSource={window.paypal.FUNDING.PAYPAL}
      createBillingAgreement={() => (
        paypalCheckoutInstance.createPayment({
         flow: 'vault',
         intent: 'authorize',
         enableShippingAddress: true,
         currency: 'USD'
        })
      )}
      onApprove={(data) => (
        paypalCheckoutInstance.tokenizePayment(data)
          .then((payload) => {
            onTokenize(payload);
        })
      )}
      onCancel={handleCancel}
      onError={handleError}
      onInit={handleInit}
    />
  );
```

And with that code I was getting warning for wrong SDK intent setting
![image](https://user-images.githubusercontent.com/17122401/101486163-879e3900-395c-11eb-90df-92d437626dce.png)
I tried to find any documentation on intent=tokenize, and to google that, but nothing.
Can someone help with this error?
Thanks, and sorry for the long post.

**Comment by crookedneighbor** [comment] 2020-12-08 16:35
:wave: PayPal made some changes around `intent` recently, which is why you're seeing that message.

Basically, if you don't pass an `intent` in the `loadPayPalSDK`, but you're using the vault flow, PayPal defaults the `intent` to `tokenize` (which is a new value for their sdk). So either set the `intent` in your `createPayment` call to `tokenize` or set the `intent` in `loadPayPalSDK` to `authorize`.

It's in our backlog to update the documentation around `intent` to clarify the behavior, but this should get you going for now.

**Comment by crookedneighbor** [comment] 2021-02-25 15:41
FYI, we're going to make an update here to update the default intent in `loadPayPalSDK` to `authorize`. It looks like `tokenize` is a value used in the orders v2 api, while Braintree is using the orders v1 api.

https://developer.paypal.com/docs/checkout/reference/customize-sdk/?mark=intent#intent

**Comment by crookedneighbor** [comment] 2021-02-25 15:41
Going to re-open this issue for now so we can update it and close it when the fix goes out.

**Comment by crookedneighbor** [comment] 2021-03-05 22:09
This is fixed in 3.74.0

**Closed by crookedneighbor** 2021-03-05 22:09 UTC

**Comment by crookedneighbor** [comment] 2021-03-17 16:08
FYI, we were seeing some issues using `authorize` as the default intent for the vault flow, so we reached out to our PayPal colleagues and confirmed that `tokenize` will work just fine. v3.75.0 changes the default intent for the vault flow to `tokenize`.

**Comment by mbillz** [comment] 2021-03-24 00:06
Hi @crookedneighbor - this warning message is very helpful! It doesn't look like the types have been updated to allow `tokenize` as an option.
aka I get `Type '"tokenize"' is not assignable to type '"capture" | "authorize" | "sale" | undefined'.` from this block:
```
      await paypalCheckoutInstance.loadPayPalSDK({
        vault: true,
        intent: 'tokenize',
        currency: prices?.current?.currency || 'USD',
      });
```

I've created a PR to update the package here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51943

**Comment by crookedneighbor** [comment] 2021-03-24 17:09
Thanks for the info. Just so you know, we don't maintain those type definitions. The next major version of the Braintree web SDK will be written in Typescript, which will (eventually) make using those type definitions unnecessary.

**Comment by jbuckner** [comment] 2021-03-24 21:32
That's great to hear, @crookedneighbor! I'm maintaining those types now so having native types would be greatly appreciated! Do you have an idea when the TypeScript SDK will be released?

**Comment by crookedneighbor** [comment] 2021-03-24 22:00
No ETA at the moment, though we are actively working on it.
