### ISSUE TITLE
braintree.client.create returns undefined in 3.45.0

### ISSUE THREAD

**Issue by derks** [braintree/braintree-web#431] opened 2019-05-23 04:35 UTC
### General information

* SDK version: 3.45.0
* Environment: Production
* Browser and OS: Chrome 74.0.3729.131 (Official Build) (64-bit) on macOS

### Issue description

As of 3.45.0, `braintree.client.create()` returns `undefined`.  For some reason, this is only in production and can not reproduce with same code and braintree configuration in development.

Production Config:

- Heroku Stack: `heroku-18`
- NodeJS: 9.11.2

Example Client Code (coffeescript):

```coffeescript
      braintree.client.create
        authorization: authorization
      , (err, instance)->
        console.log('Authorization: ' + authorization)
        console.log('Instance: ' + instance)
        console.log('Err: ' + err)
```

Resulted in:

```
Authorization: LONG-CLIENT-TOKEN-REDACTED-XXXXXXXXXXXXXXXXXXXXXX
Instance: undefined
Err: undefined
```

Downgrading to `3.44.2` resolved our issue, but we'd like to help uncover the underlying issue and fully understand if it is on our side or a bug upstream.

I am not sure what other details could be helpful here...

**Comment by quinnjn** [comment] 2019-05-23 07:11
@derks this [codepen is using braintree-web 3.45.0](https://codepen.io/braintree/pen/ZWPpPG) and it is loading fine. Here is a [codepen with your example with a production tokenization key](https://codepen.io/anon/pen/yWveJG).

So it looks like braintree-web 3.45.0 can create a client in production. Do you have any other details you can share about the issue?

**Comment by quinnjn** [comment] 2019-05-23 07:12
I also tried a [codepen with a production client token](https://codepen.io/anon/pen/YbewVZ)

**Comment by derks** [comment] 2019-05-23 18:35
@quinnjn unfortunately I don't have much more info. As mentioned... our same code base running locally (against the same backend api) works fine.

I'm sorry I'm not a frontend developer, and not deeply familiar with braintree-web. Is there anyway to enable debugging that might produce more output when I try to create the client? All I get back in undefined with no error so not really sure what to do with that.

Thanks for your help.

**Comment by crookedneighbor** [comment] 2019-05-23 18:36
Can you provide your frontend code for setting up Braintree? Or a staging site? Client tokens do not contain sensitive info, so no need to redact them.

Any way for us to actually reproduce the problem would be great.

**Comment by derks** [comment] 2019-05-23 18:41
The above coffee script was taken from the actual frontend:

```
      braintree.client.create
        authorization: authorization
      , (err, instance)->
        console.log('Authorization: ' + authorization)
        console.log('Instance: ' + instance)
        console.log('Err: ' + err)
```

It would be difficult to provide access to the full project, but is there more than that that would be relevant?  The staging site also is using BrainTree sandbox configuration and we don't have the same problem with it.

I will put some thought into how I might be able get something up.

**Comment by crookedneighbor** [comment] 2019-05-23 18:53
Well, we've provided codepens with our authorizations with that exact code and it worked just fine. You could put up a staging site with a hard coded prod client token, instead of generating one, (so you don't need to add your prod env variables to your staging site).

**Comment by derks** [comment] 2019-05-23 19:48
@crookedneighbor I ran this same code from your codepen and also using my own authorization token  in a similar heroku instance and can not reproduce either.  This frontend/angularjs-1.x code is something we inherited... so there might be (maybe probably is) something in there that is blocking this but just can't understand what being that we can't reproduce it anywhere else.

**Comment by crookedneighbor** [comment] 2019-05-23 19:50
I'm happy to take a look at a staging site if you can reproduce it there.

**Comment by derks** [comment] 2019-05-23 19:53
Right on... will work on getting that setup and circle back.

**Comment by crookedneighbor** [comment] 2019-05-23 19:54
If you'd prefer not to post it publicly to Github, you can contact our support team and reference this issue: https://help.braintreepayments.com/

**Comment by crookedneighbor** [comment] 2019-06-10 19:26
Going to close this, since there's nothing more actionable here on Github.

**Closed by crookedneighbor** 2019-06-10 19:26 UTC

**Comment by derks** [comment] 2019-06-12 02:46
@crookedneighbor thank you for the help... i've unfortunately not had a chance to standup a dedicated staging infrastructure to test this.  I will followup with the support request I've got open when I can though.
