### ISSUE TITLE
Configuration of undefined error

### ISSUE THREAD

**Issue by bluejamesbond** [braintree/braintree-web#154] opened 2016-04-08 04:31 UTC
When using Uglify, I get the following error:
```
Uncaught TypeError: Cannot set property 'configuration' of undefined'`
```

Without Uglify, it works fine.

v2.21.1

**Comment by intelliot** [comment] 2016-04-12 20:31
@bluejamesbond We're not able to reproduce this error. Could you provide steps for how to trigger it?

Also, which version of braintree.js are you using? (We don't have a v2.21.1.)

Thanks!

**Comment by mrak** [comment] 2016-04-22 18:35
Closing from lack of follow-up. Feel free to reopen this issue if you are still experiencing it and have more information for us.

**Closed by mrak** 2016-04-22 18:35 UTC
Labels: more information needed
