### ISSUE TITLE
Annoying popup always shows up

### ISSUE THREAD

**Issue by basco-johnkevin** [braintree/braintree-web#328] opened 2017-09-16 07:14 UTC
### General information

* SDK version: 2.27.0
* Environment: Sandbox & Production
* Browser and OS Version 60.0.3112.113 (Official Build) (64-bit) on MacOS 10.12.5 

### Issue description

An annoying popup that contains this message "Do you want to leave this site? Changes you made may not be saved." appears when we checkout with paypal and click a button that submits an html form. 

See screenshots below:

![1](https://user-images.githubusercontent.com/2178576/30510142-1360a9fe-9af1-11e7-8229-9380d542c7a7.jpg)
![2](https://user-images.githubusercontent.com/2178576/30510141-1350924e-9af1-11e7-9761-88e5026e2e49.jpg)
![3](https://user-images.githubusercontent.com/2178576/30510140-134c742a-9af1-11e7-9987-f33ac8dbc9aa.jpg)

How can we prevent that popup from showing up? This issue is probably related to the braintree js sdk that we're using.

**Comment by crookedneighbor** [comment] 2017-09-18 15:19
That is a built in browser feature that occurs when you attempt to leave a webpage with a form partially filled out. This is unlikely due to the Braintree SDK.

Can you provide a staging site for us to review? Or some sample code that reproduces the issue?

**Comment by crookedneighbor** [comment] 2017-09-21 20:08
I'm going to close this, because I don't think this has anything to do with the Braintree SDK, but feel free to comment here with a reproducible example if that is not the case and I'll re-open the issue.

**Closed by crookedneighbor** 2017-09-21 20:08 UTC
