### ISSUE TITLE
Drop-in freezes in loading state after calling braintree.setup()

### ISSUE THREAD

**Issue by Janekk** [braintree/braintree-web#105] opened 2015-12-02 14:45 UTC
It seems that with latest versions drop-in widget happens to freeze in the loading state after calling the `setup` method from JS client SDK (it is showing endless spinning wheel and no errors in browser console). 

I noticed this happening if `container` param is passed using the actual DOM element, not id.

**Comment by whatSocks** [comment] 2015-12-02 14:51
Yes, this is horrible! +1 on fixing it.

**Comment by ShannonStoner** [comment] 2015-12-02 14:54
Please fix this! +1

**Comment by bahrainjames** [comment] 2015-12-02 14:56
+1

**Comment by selim2006** [comment] 2015-12-02 14:58
It was working good earlier of the day we implemented it. But it seems after updating to latest versions drop-in widget happens to freeze.

**Comment by lilaconlee** [comment] 2015-12-02 16:38
We're actively looking into this issue but have been unable to replicate it so far.

• What version number of Braintree.js are you using?
• In which browsers are you seeing this issue?

Please feel free to contact support@braintreepayments.com if this issue is urgent for you.

**Comment by Janekk** [comment] 2015-12-02 17:17
@lilaconlee thanks for your prompt response. It started to pop up after we switched from ver. 2.11.x to 2.15.x (also an issue with the recent 2.17.1). It seems to be a bit random and tends to happen or not in different environments. We're using the widget within a React component. Luckily passing the element `id` instead of element itself helped to get rid of this problem, so this is not urgent

**Comment by mikep** [comment] 2015-12-02 17:25
I was also having an issue that popped up this morning after the 2.17 release. I fixed it by changing what we passed as the container in braintree.setup from a jquery object to a plain dom element.

**Comment by mandersondesign** [comment] 2015-12-02 20:23
This is an urgent issue for us. I emailed support@braintreepayments.com with more details about the issue.  Some specific info related to our case:

For the past few hours whenever a new user attempts to pay with paypal (i.e., they don't have a braintree token already, or haven't paid on the site with paypal before) the authorization process breaks. After clicking ''pay with paypal'' in the drop in UI, a new window is opened to authorize paypal with a URL of the following structure:

https://checkout.paypal.com/pwpp/2.17.2/html/braintree-frame.html#

This page refuses to load and generates the following error in braintree-paypal-internal.min.js on line 7:

Uncaught TypeError: Cannot read property 'locale' of undefined

Since this is a minified JS file, I can't really provide any more detail than this. However, it doesn't appear that the issue has any frontend workarounds (if the user wishes to pay with paypal, anyways), and I can't debug it since this authorization flow happens off-site.

**Comment by abelaska** [comment] 2015-12-02 20:41
Every version newer than 2.16.1 is affected by this bug.

**Comment by crookedneighbor** [comment] 2015-12-02 21:19
Thanks for the information. We've been able to reproduce the bug and are working on a fix.

**Comment by kyledetella** [comment] 2015-12-03 03:04
Thanks for bringing this to our attention. We have addressed the problem and released a fix which is available now as [`2.17.3`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2173).

I am going to close this issue, feel free to re-open it if you are still having issues.

**Closed by kyledetella** 2015-12-03 03:04 UTC
