### ISSUE TITLE
Chrome iOS Paypal Popup Issue

### ISSUE THREAD

**Issue by GabrielMSharp** [braintree/braintree-web#264] opened 2017-02-15 13:58 UTC
On Chrome v56.x on iOS the Paypal popup is not opening a new tab, as on Safari, and causes an issue with logging in an account, often resulting in a white page. Similar to [this bug](https://github.com/braintree/braintree-web/issues/143)

We are still on 2.27.0 of Braintree - My suspicion is 3.x would fair better. However the [aforementioned Issue](https://github.com/braintree/braintree-web/issues/143) claims a fix for this behavior in 2.22.2. Has this bug returned with the latest Chrome on iOS?

**Comment by crookedneighbor** [comment] 2017-02-15 14:51
Thanks for reporting this. We've confirmed the issue and are looking into the cause.

We've confirmed that PayPal in v3 does open up in a new tab.

**Comment by lilaconlee** [comment] 2017-02-15 20:50
@GabrielMSharp This issue (which should only have appeared when using iOS 10) should be fixed as of 2.31.0 of braintree-web. Thanks for catching this!

**Closed by lilaconlee** 2017-02-15 20:50 UTC
