### ISSUE TITLE
Hosted field times out

### ISSUE THREAD

**Issue by niteshgrg** [braintree/braintree-web#395] opened 2018-10-31 12:31 UTC
### General information

* SDK version: 3.37.0
* Environment: Sandbox
* Browser and OS: UIWebView iOS

To note. I noticed my merchantAppId is empty can that be one of the issue.
### Issue description

{"analytics":[{"kind":"web.custom.hosted-fields.load.timed-out","timestamp":1540988227}],"braintreeLibraryVersion":"braintree/web/3.37.0","_meta":{"merchantAppId":"","platform":"web","sdkVersion":"3.37.0","source":"client","integration":"dropin2","integrationType":"dropin2","sessionId":"36dddbae-f961-4068-bc3c-7b40958982b6","dropinVersion":"1.13.0"},"authorizationFingerprint":".....created_at=2018-10-31T12:03:31.913010017+0000&customer_id=85&merchant_id=...&public_key=..."}

**Comment by crookedneighbor** [comment] 2018-10-31 14:41
Closed as a duplicate of #355

**Closed by crookedneighbor** 2018-10-31 14:41 UTC
