### ISSUE TITLE
Postal Code Input issue w/Samsung Keyboard

### ISSUE THREAD

**Issue by eschie** [braintree/braintree-web#245] opened 2017-01-05 21:45 UTC
Our Android users (Marshmallow) were reporting issues (Chrome 55) inputting both expiration date and postal code, in which the cursor jumping on key input resulted incorrect information.  

We believe the update to 3.6.3 fixes the issue for the backwards expiration year, but we are still seeing issues with the postal code:

![postalcodeinput2](https://cloud.githubusercontent.com/assets/1564750/21696583/944c3086-d343-11e6-8048-1f20d020a6ec.gif)

**Comment by crookedneighbor** [comment] 2017-01-06 20:54
I'm unable to reproduce this on the Samsung test device I have. It's on `6.0.1; SM-G930P Build/MMB29M` and the Chrome version is `55.0.2883.91` using the defautl Samsung keyboard. That looks the same as what you provided.

What keyboard are you using?

Are you getting the same behavior here? http://codepen.io/braintree/pen/MyzXqG

If not, can you provide a website or github repo where I can reproduce it?

**Comment by eschie** [comment] 2017-01-06 21:09
Default Samsung Keyboard
Chrome: 55.0.2883.91
Samsung SM-J700P; Android 6.0.1; Build MMB29M.J700PVPU1APH4

Yes, we're getting the same behavior:

![postalcodepen](https://cloud.githubusercontent.com/assets/1564750/21733015/35a602ea-d411-11e6-9365-9369633d4750.gif)

**Comment by crookedneighbor** [comment] 2017-01-06 22:27
Thanks for the update. We'll try to round up some other Samsung devices for testing.

**Comment by eschie** [comment] 2017-01-10 20:00
@crookedneighbor We're also having issues on earlier versions of Android:

Samsung Galaxy S5
Android 4.4.4 (Kitkat)
Browser: Google Chrome 54

![postalbug2](https://cloud.githubusercontent.com/assets/1564750/21822146/f08cfe12-d72a-11e6-93c2-13d24fca1c5d.gif)

This also had the same effect on the codepen link.

**Comment by crookedneighbor** [comment] 2017-01-18 21:49
A fix for this should come out in the next release. We'll post here when it's ready.

**Comment by crookedneighbor** [comment] 2017-01-19 17:27
The [library we used for formatting](https://github.com/braintree/restricted-input) has been updated. We haven't deployed the fix to braintree-web yet, but if you have a moment, could you try out the Android device on this page http://braintree.github.io/restricted-input/ There is a postal code input near the bottom of the page.

**Comment by eschie** [comment] 2017-01-19 22:09
It looks to be fixed on Chrome for that Android, but we discovered a new issue for Samsung Galaxy J7 native browser where the postal code does not input at all, even on the restricted input:

![restinputsmj7](https://cloud.githubusercontent.com/assets/1564750/22127225/eb6fc938-de4f-11e6-898a-7e9d60dcd1b1.gif)

And not on our site which is using 3.6.3:

![j7postal](https://cloud.githubusercontent.com/assets/1564750/22127468/d166ab3c-de50-11e6-8f5a-87ef29aed1af.gif)

**Comment by quinnjn** [comment] 2017-01-19 23:04
@eschie we really appreciate the feedback you're giving us, and I'm glad that the current release fixes the postal code issue for Chrome!

We're investigating this new issue, stay tuned.

**Comment by intelliot** [comment] 2017-01-23 21:37
@eschie We're unable to reproduce this on the Samsung test device we have.

When using the Samsung native browser, our test device's user agent is:

`Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG SPH-L720T Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36`

Also, we're using Samsung keyboard Version 4.0 (according to `Application manager`).

What's your user agent, browser version, and/or keyboard version?

**Comment by eschie** [comment] 2017-01-23 22:12
@intelliot I'm on Samsung Native Browser Version 4.0.30-19

`Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-J700P Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`

Samsung Keyboard Version: 1.2.93 (according to About Keyboard as it doesn't show up in Application manager)

**Comment by intelliot** [comment] 2017-01-27 00:32
@eschie Thanks! We reproduced the issue on Samsung Browser 4.0. We're going to disable restricted input for user agents that contain `SamsungBrowser` - we'll update here when this change is released.

**Comment by intelliot** [comment] 2017-02-01 17:21
@eschie We have released version `3.7.0` which disables input formatting for Samsung Internet browsers. Thanks for your help!

**Closed by intelliot** 2017-02-01 17:21 UTC
