### ISSUE TITLE
2nd autocomplete not working across hosted fields

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree-web#479] opened 2019-12-06 05:53 UTC
### General information

* SDK version: 3.53.0 and 3.55.0
* Environment: Sandbox
* Browser and OS : 78.0.3904.108-1 and Ubuntu Linux 

### Issue description

Autocompleting credit card hosted fields card number and expiration from browser's stored credit card payment methods works on first attempt. e.g. Auto-completion on card number will also auto-complete the expiration and vice-versa. That is, auto-completion works across hosted fields.

If you then clear the auto-completed card number and expiration hosted fields, then attempt **ANOTHER / 2nd** autocomplete on card number, the expiration is not auto-completed.

1) See attached braintree-test.html and replace the 'sandbox_XXXXXX' token with a valid sandbox authorisation token.
2) Host the attached braintree-test.html in a web server and make sure it is served via HTTPS and that Chrome recognises that entire certificate chain.
3) Ensure you have stored credit card numbers in Chrome.
4) Auto-populate from either card number hosted field or expiration date hosted field using the card number suggested by Chrome.
5) After both hosted fields are auto-populated, clear both the card number and expiration hosted fields.
6) Do another auto-populate from card number suggested by Chrome.
7) Card number hosted field is auto-populated, but notice that the expiration hosted field is NOT auto-populated. 

[braintree-test.zip](https://github.com/braintree/braintree-web/files/3930632/braintree-test.zip)

**Comment by jmsjr** [comment] 2019-12-06 07:33
Actually, there is also another bug that I discovered,

After loading the page, if you 1st-time auto-complete from the expiration hosted field, the card number is *NOT* autocompleted.

**Comment by crookedneighbor** [comment] 2019-12-06 14:48
So the way hosted fields autocomplete works is that the number frame contains a bunch of hidden inputs for the other parts of the credit card. When you start an autocomplete action from the number frame, it populates the hidden inputs inside it and then post messages those values out to the rest of the hosted fields iframes on your page to fill those in.

> If you then clear the auto-completed card number and expiration hosted fields, then attempt ANOTHER / 2nd autocomplete on card number, the expiration is not auto-completed.

Given the above structure, this makes sense, since the hidden expiration date in the number iframe has _not_ changed, so there's no need to fill it. And since there's no need to fill it, there's no need to message it out to the rest of the iframes.

Definitely an edge case here we should handle, so thanks for bringing it up. Should be pretty straightforward to keep them in sync.

> After loading the page, auto-completing from the expiration hosted field does NOT autocomplete the card number hosted field .. even if it is the first-time you try to auto-complete on the page.

This is expected behavior, because the extra inputs are only present in the number iframe. We made this decision to keep the code simple, but it may be that we instead need to insert the extra inputs in all frames (especially to support autocomplete in the cardholder name field, see #480)

These are added to our backlog.

**Comment by crookedneighbor** [comment] 2020-09-21 19:05
Fixed in v3.66.0 (note that [npm is currently having issues publishing packages](https://status.npmjs.org/incidents/13n2894dytyt) ), so this is available via our CDN, but may take a while to be available on npm.

**Closed by crookedneighbor** 2020-09-21 19:05 UTC
