### ISSUE TITLE
setup is not removing previously created elements

### ISSUE THREAD

**Issue by passionkind** [braintree/braintree-web#169] opened 2016-06-02 08:45 UTC
I have setup the paypal express checkout by calling `braintreeWeb.setup`. This works perfectly fine, but when I add or remove items, I create a new payment token and have to re-setup the express checkout to request the refreshed price.

I haven't found any other way yet but calling `braintreeWeb.setup` on each update and having a `MutationObserver` taking care of removing redundant buttons and dark transparent overlays. 

Weird thing is that after I call setup again, the previously added buttons do reflect the new price when the popup opens. So if the script would just check if the button already exists in the container or remove and readd it, that would help a lot!

Or is there any other way to re-init the checkout without adding further buttons / overlays ?

**Comment by mrak** [comment] 2016-06-02 17:31
Have you tried our [teardown](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#teardown) method? It should clean up any elements created by `.setup()`.

**Comment by passionkind** [comment] 2016-06-03 09:59
teardown to the rescue ! helps a lot, thank you !

But is it possible that teardown does not remove the dark overlay? I have now called setup and teardown several times and when I do open the express popup, the background of my app becomes completely black.

**Comment by mrak** [comment] 2016-06-03 16:40
if the black overlay is in place (upon spawning the PayPal popup) and you call `teardown`, does the overlay go away?

**Comment by EvanHahn** [comment] 2016-06-09 16:21
@passionkind Any update here?

**Comment by passionkind** [comment] 2016-06-10 09:14
The black background is not being removed when calling teardown. I'm potentially calling the setup and teardown multiple times before the user actually sees the popup. 


![screenshot](http://i.imgur.com/XhjsjO2.jpg?1)

**Comment by mrak** [comment] 2016-06-10 16:27
I've created a simple test app that lets you teardown/setup braintree.js many times.

https://mrak.github.io/teardown-overlay-test/

Is it possible that there are several instances of braintree.js that have been set up but not torn down?

**Comment by lchhieu** [comment] 2016-06-16 08:05
I got an error is: Uncaught TypeError: Cannot read property 'teardown' of undefined

**Comment by crookedneighbor** [comment] 2016-06-16 13:03
@lchhieu Are you saying you're getting that error on @mrak's test app? I can't reproduce that. What browser and OS are you using?

**Comment by mrak** [comment] 2016-06-23 16:25
Closing. Reopen if more information becomes available.

**Closed by mrak** 2016-06-23 16:25 UTC
Labels: more information needed

**Comment by sygcom** [comment] 2016-11-09 11:14
@lchhieu I am getting the same erro while calling the teardown method()

**Comment by crookedneighbor** [comment] 2016-11-09 16:03
@sygcom Are you getting that message in the test app we provided: https://mrak.github.io/teardown-overlay-test/

If so, what browser and os are you using?

If not, what browser and os are you using _and_ do you have a reproducible example?

**Comment by crookedneighbor** [comment] 2017-09-05 11:31
Are you getting that message in the test app we provided? https://mrak.github.io/teardown-overlay-test/

**Comment by EkoJr** [comment] 2017-09-05 16:57
I wasn't able to get my head around that. Just been trying to troubleshoot with the knowledge I have, but figured I would post an error and a call stack at least.

**Comment by lilaconlee** [comment] 2017-09-05 19:18
Would you mind updating your version of the braintree-web library? If you're using a script tag that would be `https://js.braintreegateway.com/js/braintree-2.32.0.min.js`. 

Otherwise if you can provide us with a staging site, demo app, or even a code snippet where we can reproduce the issue we can help you debug the issue. If you rather not share that on GitHub, feel free to [contact Braintree support](https://developers.braintreepayments.com/forms/contact).

**Comment by EkoJr** [comment] 2017-09-05 19:28
I noticed my version was different as well, and I checked to see if I had the latest Braintree extension for WooCommerce.

Which I also noticed the Author was WooCommerce...is this extension even part of BrainTree's developer crew?

[WooCommerce PayPal Powered by Braintree Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/)

I also found the same issue reported here. https://wordpress.org/support/topic/spinning-wheel-during-update-cart/

**Comment by EkoJr** [comment] 2017-09-05 19:56
Also, I migrated to a Live site about a week or two ago, and the stage site doesn't fully reflect the Live site. I'm also just someone helping someone else out with the development.

With what I mentioned in the last comment, I was curious if this is even within your guy's scope.

**Comment by crookedneighbor** [comment] 2017-09-07 13:24
WooCommerce maintains that plugin. Not Braintree.
