### ISSUE TITLE
GetConfiguration `window` is not defined in SSR Isomorphic Applications.

### ISSUE THREAD

**Issue by KempfCreative** [braintree/braintree-web#531] opened 2020-10-26 20:39 UTC
### General information

* SDK version: 3.64.2
* Environment: Production
* Browser and OS: N/A
### Issue description

My team uses Braintree in an isomorphic React application (nextjs). This means that some of the modules get loaded on the server side and client side, depending on the user journey. We have seen the `getConfiguration` call inside the client/get-configuration.js, is throwing a fatal error in the server side (NodeJS) context:

```
ReferenceError null.<anonymous>(braintree-web.client:get-configuration)
errorwindow is not defined
```

To be fair, I understand that this is the "web" SDK, and no explicit support for server side is present. However, due to the small amount of lift it would take to make this particular function type safe, it seems like an obvious win.

```
function getConfiguration(authData) {
  return new Promise(function (resolve, reject) {
    var configuration, attrs, configUrl, reqOptions;
    var sessionId = uuid();
    var analyticsMetadata = {
      merchantAppId: window.location.host,
      platform: constants.PLATFORM,
      sdkVersion: constants.VERSION,
      source: constants.SOURCE,
      integration: constants.INTEGRATION,
      integrationType: constants.INTEGRATION,
      sessionId: sessionId
    };
```

By adding a check that `window` is available in the current execution context, similar to how the `applePayWebSession` does it:
```
var applePayWebSession = {
      validationUrl: options.validationURL,
      domainName: options.domainName || window.location.hostname,
      merchantIdentifier: options.merchantIdentifier || self.merchantIdentifier
    };
```
it could be possible to avoid this error and continue to render the page.

At the very least, a fallback value for `merchantAppId` would be ideal so as to not cause fatal executions on the app side.

If you would like a PR to be opened, I can do that as well.

**Comment by crookedneighbor** [comment] 2020-10-26 20:49
How is `getConfiguration` getting called on your server side? It shouldn't be available until after `create` is called, so it shouldn't happen until the page is actually loaded, right?

**Comment by crookedneighbor** [comment] 2020-10-26 20:54
> To be fair, I understand that this is the "web" SDK, and no explicit support for server side is present.

To clarify on this, we've been careful to construct the sdk in such a way that the window is only accessed from within function calls, so that it can be used specifically for server side rendering, so to find out that it's not actually working as intended is a little alarming.

**Comment by crookedneighbor** [comment] 2020-10-28 15:44
@KempfCreative any update on how we can reproduce it?

**Comment by KempfCreative** [comment] 2020-10-28 17:42
Sorry my computers battery died right after I wrote this and it is currently being repaired. 

If you could please keep this open for a week even with inactivity I would appreciate it.

**Comment by crookedneighbor** [comment] 2020-10-28 17:59
I'm fine leaving it open for now.

**Comment by crookedneighbor** [comment] 2020-11-05 20:28
@KempfCreative any updates on this? Would love to explore this more.

**Comment by KempfCreative** [comment] 2020-11-10 04:19
@crookedneighbor I've tried a variety of ways to diagnose how this is happening without success. Over a 90 day span, I only see this error 26 times (out of hundreds of thousands of instances), so perhaps it is load related.

Either way, no luck with even triggering a debugger locally, so I guess we can close this.

**Comment by crookedneighbor** [comment] 2020-11-10 15:23
Is it possible that you're calling `braintree.client.create` on the server side in some cases? If so, the `create` methods should only ever be called on the browser. Importing them on the server should be just fine, but actually calling `create` should only happen in the browser.

Will close this now, but if you find more information about why you're seeing this occasionally, let us know.

**Closed by crookedneighbor** 2020-11-10 15:23 UTC
