### ISSUE TITLE
braintree.client object not defined in phantomjs

### ISSUE THREAD

**Issue by johnbburg** [braintree/braintree-web#317] opened 2017-08-10 17:26 UTC
* SDK version: 3.7
* Environment: Testing
* Browser and OS Phantomjs 2.1.1 on Ubuntu 16.10

I'm developing some automated tests for a project, and the Braintree client doesn't seem to be fully initialized in the context of Phanomjs, braintree.client is undefined. Is there anything obvious from the developers that might cause this? Maybe some tips on debugging the issue? I don't seem to be getting any errors from the braintree code itself.

**Comment by johnbburg** [comment] 2017-08-10 17:51
I did switch to the latest 3.22 release, and I run into the same issue.

**Comment by crookedneighbor** [comment] 2017-08-10 18:15
How are you loading the braintree-web code in your tests? 

Can you provide an example repo on Github that reproduces the behavior?

**Comment by johnbburg** [comment] 2017-08-10 19:16
An example of the page in question is https://www.mercycorps.org/donate. I can't readily provide access to the private repo. The braintree code is included as:

```
<script type="text/javascript" src="//js.braintreegateway.com/web/3.22.0/js/client.min.js"></script>
<script type="text/javascript" src="//js.braintreegateway.com/web/3.22.0/js/hosted-fields.min.js"></script>
<script type="text/javascript" src="//js.braintreegateway.com/web/3.22.0/js/data-collector.min.js"></script>
```

I'm using this phantomjs script to debug the page:

```
var page = require('webpage').create();

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

page.open('https://localhost:8081/donate', function(status) {
  page.evaluate(function() {
    setInterval(function() {
      for(var propName in braintree) {
        propValue = braintree[propName]
        console.log(propName,propValue);
      }    
      console.log(zero);
    }, 5000);
  });
  //phantom.exit();
});
```

This works fine pointing at the live site, however, locally, the braintree.client property is undefined.

**Comment by crookedneighbor** [comment] 2017-08-11 13:51
Couple of things I had to do to make it work.

1. I had to set my localhost host url to `http://` instead of `https://`. If you have your localhost set up to server over `https`, you can ignore this bit.

2. I had to set my asset urls from `//js.braintreegateway...` to `https://js.braintreegateway...`. For some reason, when phantomjs evaluates that protocol over localhost, it doesn't actually load.

Here's some demo code that works for me:

```js
var page = require('webpage').create();

page.onConsoleMessage = function(msg) {
  console.log(msg);
};

page.open('http://localhost:8081/', function(status) {
  if (status === "success") {
    page.evaluate(function() {
      Object.keys(braintree).forEach(function (component) {
        // result in console:
        // client [object Object]
        // hostedFields [object Object]
        // dataCollector [object Object]
        console.log(component, braintree[component]);
      });
    });
    phantom.exit();
  } else {
    console.log('Page failed to load');
    phantom.exit();
  }
});
```

I think this solves your issue, so I'm going to close this now. Feel free to comment back here if you have additional questions.

**Closed by crookedneighbor** 2017-08-11 13:51 UTC
