### ISSUE TITLE
`Cannot read property 'sjcl' of undefined`

### ISSUE THREAD

**Issue by clindsey** [braintree/braintree-web#228] opened 2016-10-26 23:05 UTC
I'm attempting run my tests using [ava](https://github.com/avajs/ava) and [jsdom](https://github.com/tmpvar/jsdom) but I get the error `Cannot read property 'sjcl' of undefined` from braintree-web.

I haven't been able to find any helpful resources on how this should be handled in headless testing.

**Comment by crookedneighbor** [comment] 2016-10-27 14:15
Can you make a repo with a reproducible case for this?

**Comment by crookedneighbor** [comment] 2016-10-28 21:05
Also, what version of braintree-web are you using?

**Comment by crookedneighbor** [comment] 2016-10-31 13:28
@clindsey I'm going to close this, since we haven't received a response from you, but if you still need help, feel free to re-open this issue.

**Closed by crookedneighbor** 2016-10-31 13:28 UTC

**Comment by SokratisVidros** [comment] 2016-11-02 09:23
I am also facing the same issue using mocha, sinon and jsdom.

```
TypeError: Cannot read property 'sjcl' of undefined
    at Object.<anonymous> (..my_project/node_modules/braintree-web/dist/braintree.js:5:26279)
    at Object.i.189 (..my_project/node_modules/braintree-web/dist/braintree.js:5:27655)
    at o (..my_project/node_modules/braintree-web/dist/braintree.js:3:561)
    at ..my_project/node_modules/braintree-web/dist/braintree.js:3:612
    at Object.i.188.187 (..my_project/node_modules/braintree-web/dist/braintree.js:5:25888)
    at o (..my_project/node_modules/braintree-web/dist/braintree.js:3:561)
    at ..my_project/node_modules/braintree-web/dist/braintree.js:3:612
    at Object.<anonymous> (..my_project/node_modules/braintree-web/dist/braintree.js:5:1145)
    at Object.i.163.14 (..my_project/node_modules/braintree-web/dist/braintree.js:5:4089)
    at o (..my_project/node_modules/braintree-web/dist/braintree.js:3:561)
```

Any help would be greatly appreciated.

**Comment by crookedneighbor** [comment] 2016-11-02 14:45
Looks like you're using v2 of braintree-web. If you're not using Drop-In, I'd recommend upgrading to v3 of braintree-web, which is requirable in non-browser environments. 

If you are using Drop-In, you will likely have to mock the global window object and various browser specific APIs.

If you provide a simple reproducible example, I will attempt to help you with it.

**Comment by SokratisVidros** [comment] 2016-11-02 15:17
I am afraid i have to use the v2 and the drop-in UI as my payment form is enclosed in a shadow root.
In my JSDom setup file the window object as well as various namespaces are mocked. Do you have a rough estimate of what needs to be mocked?

Thanks!

**Comment by crookedneighbor** [comment] 2016-11-02 15:34
If you make a minimal github repo or gist that illustrates the problem, I'm happy to take a look at it.

**Comment by SokratisVidros** [comment] 2016-11-03 08:11
I've prepared a gist with my JSDOM setup. The error is invoked before the actual test code starts running.

https://gist.github.com/SokratisVidros/e4350345e8722c51f8210e99c7630d6d

**Comment by crookedneighbor** [comment] 2016-11-03 14:55
@SokratisVidros @clindsey 

Add `global.Braintree = {};` in your set up file and it should work.

**Comment by SokratisVidros** [comment] 2016-11-03 15:23
Worked like a charm! Thanks a lot!

Regards,

---
*Sokratis Vidros*
Senior Software Engineer @ Workable <http://workable.com/>

2016-11-03 16:55 GMT+02:00 Blade Barringer <notifications@github.com>:
