### ISSUE TITLE
Credit Card Autofill Does Not Work

### ISSUE THREAD

**Issue by dedman** [braintree/braintree-web#239] opened 2016-12-05 15:23 UTC
So following on from #216, it would be great if the expiry date autofill on Safari could be fixed. The credit card number autofill is now at least working, however to look as professional as most other sites out there, we really need autofill of expiry date too. 

I appreciate that this won't be an easy ticket, and I don't expect it to be fixed next week or even next month, but I really think it will be worthwhile in the long run. Even if Braintree needs to open a ticket with Apple/Safari to get it to work.

Thanks for a great product!

**Comment by crookedneighbor** [comment] 2016-12-05 15:26
Copying over my comment about this from the previous issue:

> In most browsers, for credit card autofill to work, you need multiple credit card fields. IE, the number and expiration date, etc. Safari is a little different in that it will prompt for autofill with just the credit card number.
> That's why Safari will prompt for the number while other browsers will not, because in the context of the Hosted Field iframe, there is just the credit card number input. However, that is also why the expiration date is not being populated, because although it looks like it's on the same form on your page, the input is actually isolated in the Hosted Fields iframe, so it doesn't have access to the other inputs.
> There may be a way to populate the other card fields by having dummy inputs for each credit card field in each iframe to capture that data, but it may wreak havoc with screen readers (IE, what happens when the screen reader sees many duplicate card fields on a page), so we will need to be very careful before we implement something like that.

I'm also updating the issue name to be about autofill in general, since if we can figure out a way to enable autofill across fields, it should not be limited to Safari.

**Comment by sreidaf** [comment] 2016-12-14 15:04
I'm also having a couple of autofill issues : 

- Hosted fields are not autofilled in Chrome. If I change type="tel" to type="text", for credit card and expiry date, they work. However, noticed the reason here is for mobile keyboard choice - https://github.com/braintree/braintree-web/issues/133. I then tried autocomplete="cc-number" and, leaving type="tel", this worked (see https://html.spec.whatwg.org/multipage/forms.html#inappropriate-for-the-control)
- When auto formatting is enabled in the hosted field for credit cards, Lastpass does not autofill the field correctly for an Amex card (maybe others too) - 2 digits are missing. If auto formatting is disabled, autofill works.

**Comment by Chocksy** [comment] 2017-01-05 22:01
There is an issue with 1password as well as the formatting does not work for credit card: http://take.ms/YWwFU

I saw that you guys had a fix for Safari but what can we do for this thing? It seems like if you have a autofill/paste of the credit card number that has spaces in it the formatting eats one of the numbers after the space

**Comment by okovpashko** [comment] 2017-02-10 23:49
We also have an issue with 1Password autofill so we had to turn off autoformatting for the number field.
I've made an investigation about this issue and found that 1Password fills input directly via DOM property and then fires several events for imitating real text input.
Here is the snippet from the 1Password extension:
```
function ba(a) {
        var b = a.value
          , c = a.ownerDocument.createEvent('HTMLEvents')
          , d = a.ownerDocument.createEvent('HTMLEvents');
        a.dispatchEvent(t(a, 'keydown', 0, 0));
        a.dispatchEvent(t(a, 'keypress', 0, 0));
        a.dispatchEvent(t(a, 'keyup', 0, 0));
        d.initEvent('input', !0, !0);
        a.dispatchEvent(d);
        c.initEvent('change', !0, !0);
        a.dispatchEvent(c);
        a.blur();
        if ('' === a.value || a.dataset['com.agilebits.onepassword.initialValue'] && a.value === a.dataset['com.agilebits.onepassword.initialValue'])
                a.value = b
}
```
Even if it's not easy to understand all the details it's can be understood what events are fired.

Next, I tried to figure out how the formatter works and I found that it unformats input after the `keypress` event if the key can mutate input value:
```
self.inputElement.addEventListener('keypress', function (event) {
    if (keyCannotMutateValue(event)) { return; }
    self._unformatInput(event);
  });
```
But `keyCannotMutateValue` function doesn't have any logic for detecting simulated keypress.

I'm not sure if it's ok to rely on 0 in keyCode to detect 1Password autofill but I hope that this information could help you to somehow fix this issue.

**Comment by okovpashko** [comment] 2017-02-11 00:06
We also faced this issue. I've created #262 related exactly to 1Password autofill.

**Comment by eschie** [comment] 2017-05-31 18:39
There is also an intermittent issue with Dashlane. I've created #298 with more details.

**Comment by crookedneighbor** [comment] 2017-06-07 19:08
3.18.0 is now out which includes fixes for autofill. 

If you'd like to see the code for the fix, you can look at [this file](https://github.com/braintree/braintree-web/commit/9011235f6b12399c1d5744f163eed581b5deb607#diff-21173be434c6b00816b3fbdb819ea2d6). Essentially we had to insert a form and the other inputs into the number iframe. When the autofill values populate, the iframe post messages out the expiration date (and in the case of LastPass, cvv) to the other iframes.

Tested on Google Chrome, Safari, LastPass, 1Password, Dashlane.

Firefox does not have a built in credit card manager.

**Comment by crookedneighbor** [comment] 2017-06-07 19:09
If you see a problem with autofill, feel free to comment about it here.

**Comment by umair-farooq** [comment] 2017-07-13 13:00
We have integrated braintree in our eCommerce site and currently just completed development. 

During QA, the QA engineer found an unexpected behavior related to auto filling card field from saved credit cards in browser. 

By default, there is no placeholder attribute in any of the hosted fields. But when a card is selected from the list of saved credit card in the browser, the credit card number and expiration date are filled and placeholder="null" is added in the expiration date is added. Now if the expiration date is removed, then the "null" placeholder is shown (as shown in attached image).

Can you please verify if this issue is from your side ? If yes, when can we expect a fix for it. 
![placeholder-null](https://user-images.githubusercontent.com/21168525/28167447-1b4b63c2-67f5-11e7-999d-62018500dfe3.jpg)

**Comment by crookedneighbor** [comment] 2017-07-13 16:55
This is definitely a bug in the SDK. I've [pinpointed the cause](https://github.com/braintree/braintree-web/blob/63d2e7a300630a1e23fc8a69afed0083f7518794/src/hosted-fields/internal/index.js#L146-L153) and this should be fixed in the next release.

**Comment by crookedneighbor** [comment] 2017-07-19 19:35
@umair-farooq This is fixed in v3.20.0

**Comment by wangjames** [comment] 2017-10-24 00:17
@crookedneighbor 

For the expiration date and expiration month fields, if you choose to style the fields with the select option, autofill with a credit card on Chrome and Safari does not work for numbers between 01 to 09. However, if your card has an expiration month between 10 to 12, the option is selected correctly.  I'm guessing this has something to do with the select options not recognizing 01 as 1?

![autofillerror](https://user-images.githubusercontent.com/8403088/31919272-024fbb86-b816-11e7-957b-b3bd3609b0e3.png)

Thanks for any help you can give!

**Comment by crookedneighbor** [comment] 2017-10-24 15:48
@wangjames This is definitely a bug. Can you open up a new issue so we can track it?

**Comment by simeyla** [comment] 2019-01-17 04:01
> If you see a problem with autofill, feel free to comment about it here.

@crookedneighbor 
Google Chrome autofill has an issue with reformatting (I'm still in development - using **hosted fields**). It's not doing it on your site for either hosted fields or drop-in so I think maybe it's a regression. I'm using the latest version.

![image](https://user-images.githubusercontent.com/3656278/51294636-ad1ca500-19c8-11e9-9a84-3d394d66e30a.png)

When I click the card in the Chrome UI to confirm it reformats to add spaces, but in doing so loses the last 3 digits*:

![image](https://user-images.githubusercontent.com/3656278/51294673-e0f7ca80-19c8-11e9-9224-a9b2bc9e7df9.png)

    "braintree-web": "^3.42.0",

* When using a real card it is indeed the last 3 lost (you obviously can't tell from the test card)

**Comment by simeyla** [comment] 2019-01-17 04:55
@crookedneighbor  thanks for the speedy reply.

At first I wasn't able to duplicate it with your codepen , but then I tried opening it in 'iPhone' device mode. And it then did have the same problem. You must be in device testing mode, not just have the javascript console open.

I stored your test card 378734493671000 (no spaces) in Chrome's built in 'vault' and when I selected it I got the following.

![image](https://user-images.githubusercontent.com/3656278/51296188-b4937c80-19cf-11e9-97c2-c67046d16e41.png)

As you can see it stripped out a 3 and a 6! 

Same behavior in both these versions:
> Windows Version 71.0.3578.98 (Official Build) (64-bit)
> Windows Version 73.0.3673.0 (Official Build) canary (64-bit)

It seems like if the page is *loaded* in device simulation mode, even if you switch back to full screen desktop view. If I then refresh the page (in full desktop view) it works fully as normal.

So hopefully (very good for end users!) this isn't likely to happen to a non-developer, but it is certainly odd behavior and hopefully you can fix it because it just slows down development.  

The fact that it's stripping out numbers at particular indexes seems to suggest it is 'fixable'.

**Comment by crookedneighbor** [comment] 2019-01-25 15:15
Since this is only reproducible in dev tools for simulated browsing, this doesn't seem like a high priority and I'm going to close this.

If you'd like to investigate it more thoroughly, feel free to take a look at our formatting library and open a PR https://github.com/braintree/restricted-input

**Closed by crookedneighbor** 2019-01-25 15:15 UTC

**Comment by simeyla** [comment] 2019-08-23 08:55
@crookedneighbor seems to work fine now :-)
