### ISSUE TITLE
ApplePay issue

### ISSUE THREAD

**Issue by 719media** [braintree/braintree-web#365] opened 2018-05-10 04:53 UTC
Experiencing an error with ApplePay. Happens when clicking the ApplePay button. Narrowed the issue down to this part of the code:

https://github.com/braintree/braintree-web/blob/f5cea4716853fdb011d55116341931304cdfdcca/src/apple-pay/apple-pay.js#L103-L115

Error:
`undefined is not an object (evaluating 'applePay.supportedNetworks.map')`

debugging the `applePay` object yields:

`{"countryCode":"US","currencyCode":"USD","merchantIdentifier":"****","supportedCardBrands":["visa","masterCard","amex","discover"]}`

(merchantIdentifier redacted)

I'm using the latest Safari. Error happens on both iOS and macOS (latest Safari). Seems like this is a rather critical problem if it is what it looks like? supportedNetworks instead of supportedCardBrands? If so, then nobody can process ApplePay who is using the createPaymentRequest method because of JS error I believe.

**Comment by crookedneighbor** [comment] 2018-05-10 11:51
What version of the SDK are you using?

**Comment by crookedneighbor** [comment] 2018-05-10 12:42
Confirmed that this was due to some configuration work that went out with 3.33.0. As a quick fix, pinning to 3.32.1 will fix the issue. Will update here when it's fixed.

**Comment by crookedneighbor** [comment] 2018-05-10 16:33
An update here, this is occurring only in sandbox, not in production. It'll be fixed in sandbox with the next release.

**Comment by 719media** [comment] 2018-05-10 16:34
It seems to be happening on production for me.

**Comment by crookedneighbor** [comment] 2018-05-10 16:35
What's your public merchant id?

**Comment by crookedneighbor** [comment] 2018-05-10 16:36
And when was the last time you checked in prod? We just turned off the configuration change in prod that was causing this bug.

**Comment by 719media** [comment] 2018-05-10 16:38
Ah, I didn't know you had that ability to fix the error without deploying a new client version. I sent you an email with some information. I'll check now.

**Comment by 719media** [comment] 2018-05-10 16:47
v3.33 is working on production now. Thank you for the fix.

**Closed** 2018-05-14 15:43 UTC
