### ISSUE TITLE
With formatInput: false, Javascript validation is done incorrectly

### ISSUE THREAD

**Issue by pdg137** [braintree/braintree-web#241] opened 2016-12-08 23:08 UTC
When using the `formatInput: false` option with hosted fields, Braintree doesn't validate inputs correctly: entering "4111-1111-1111-1111", for example, generates an unusable nonce with card type "Unknown".

Example: http://codepen.io/anon/pen/rWKoMQ

**Comment by crookedneighbor** [comment] 2016-12-09 17:09
Thanks for reporting this. I'm working on a fix for this.

**Comment by crookedneighbor** [comment] 2016-12-13 22:33
This has been fixed in v3.6.2 which we've just released.

**Comment by pdg137** [comment] 2018-04-25 19:26
This bug seems to be back in recent releases of braintree.js.  Can you get it fixed again?

Updated example for 3.32.1: https://codepen.io/anon/pen/jxrXMW

**Comment by crookedneighbor** [comment] 2018-04-25 19:31
I'm not able to reproduce in the codepen you provided.

Typing in `4111-1111-1111-1111` tokenizes just fine.

**Comment by crookedneighbor** [comment] 2018-04-25 19:32
Never mind, I misread it. Looking into it.

**Comment by crookedneighbor** [comment] 2018-04-25 19:39
Looks like this regression happened way back in 3.8.0. Looks like a PR that was in progress didn't handle the merge conflicts correctly. We'll get this fixed.

**Comment by pdg137** [comment] 2018-04-25 19:56
Thanks. By the way, in case anyone else comes here looking for a workaround, I noticed that despite the card type being "Unknown", the nonce can actually be processed, and the credit card appears normal in the vault.

**Comment by crookedneighbor** [comment] 2018-05-07 18:52
This has been fixed in 3.33.0

**Closed by crookedneighbor** 2018-05-07 18:52 UTC
Labels: Hosted Fields, bug
