### ISSUE TITLE
payment_methods/tokenxxxxxxxxx/three_d_secure/lookup returns 404

### ISSUE THREAD

**Issue by lingwooc** [braintree/braintree-web#518] opened 2020-08-13 20:42 UTC
### General information

* SDK version: 3.51.0
* Environment: Sandbox

### Issue description

When attempting to processes a sale (incidentally in magento 2.3.5-p2 with "gene/module-braintree": "4.0.4") which uses your sdk 3.51.0.

There is a 404 returned from:
https://api.sandbox.braintreegateway.com/merchants/xxxxxxxxxxx/client_api/v1/payment_methods/tokenxxxxxxxxx/three_d_secure/lookup

This is called from https://js.braintreegateway.com/web/3.51.0/js/three-d-secure.min.js which also generates the url so I don't think the bug is in the magento module.

Looks like either your library or your api has an issue.

**Comment by crookedneighbor** [comment] 2020-08-13 20:49
Most likely the token you are sending has already been consumed, which is why it's resulting in a 404. Are you possibly calling `lookup` twice with the token?

**Comment by crookedneighbor** [comment] 2020-08-13 20:50
or rather calling `verifyCard` twice, which under the hood makes the call to do the api lookup call.

**Comment by lingwooc** [comment] 2020-08-13 21:53
Thanks for the very quick response! Yup looks like the url is called twice _but_ verifyCard is called only once (verified in debugger). First response from this url is 200 (which seems positive), second is a 404 which at least appears sensible now.

The calls seem to happen more or less simultaneously in https://js.braintreegateway.com/web/3.51.0/js/client.js at line 1354
`req.send(prepBody(method, body));`

**Comment by lingwooc** [comment] 2020-08-13 22:14
Whatever is going on its doing it with 3.64.2 as well and I'm using chrome. This is very strange.

The request with the 200 response has no initiator, the 404 has client.js. What could possibly be doing that?

**Comment by crookedneighbor** [comment] 2020-08-14 01:04
Do you have a staging sight that can reproduce it? 

When I look in the inspector all I see is the one lookup call, with an `OPTIONS` portion and a `POST` portion.

**Comment by lingwooc** [comment] 2020-08-14 21:03
@crookedneighbor I'm not surprised you can't see it on your copy. There is no way this could be broken like this in general! Thanks for offering to take a look. I really appreciate it.

I've got a staging site here:
https://www-dev-96uqydnwbv.downtoearthlancaster.co.uk

This is using v3.51.0 of your SDK as this is the version provided by the module I'm using (and the newer version didn't help). It is hooked up to the sandbox api and the credentials have been verified. I've also dropped minification for the key files.

Add any old product to the basket, checkout with a UK address (put in 10 Downing Street in and autocomplete will do the rest). I'm using the test card number suggested. No payment will go through, there is an error on the page and more in the console.

**Comment by crookedneighbor** [comment] 2020-08-17 16:44
I was able to reproduce on your staging site, but not on any of my test integrations. I'll keep digging, there must be something wonky going on.

I did notice some strange stuff with how your plugin is integrated. It's specifying version 2 for creating the 3ds component but is not sending along the bin from the credit card and is passing a `addFrame` and `removeFrame` functions which will never be called.

It's also not creating the 3ds component until right before verification needs to happen, rather than having it setup along with hosted fields.

I don't _think_ any of those should cause the behavior we're seeing on the staging site, but will try to reproduce some of those on my test integrations just in case.

**Comment by crookedneighbor** [comment] 2020-08-17 17:19
I was still unable to reproduce on my test integration until I grabbed your client token and used that to setup. Then I got the issue immediately, which indicates there is something wrong with how your account is set up. 

I've let the support rep you're working with know what I found and they are working with our 3D Secure team to identify what is going on with your account.

Since it doesn't look like there's an issue with the SDK itself, I'm going to close this issue and you can continue receiving help from the support ticket you opened.

**Closed by crookedneighbor** 2020-08-17 17:19 UTC

**Comment by lingwooc** [comment] 2020-08-17 18:45
@crookedneighbor thanks for your help. I'm glad I wasn't going mad!

If it's implemented weirdly in that module it might be worth your while getting in touch. That module is the "official" braintree integration for magento2, it is actually integrated into the latest magento release (2.4) now.

**Comment by crookedneighbor** [comment] 2020-08-17 20:32
Looks like the current version is up to date: https://github.com/magento/magento2/blob/dcc962efc5ad12717c6eac0f10cf822780dd3f4a/app/code/Magento/Braintree/view/frontend/web/js/view/payment/3d-secure.js#L41-L47

So you likely need to update your integration with magento. (this won't solve your current problem, will just clean up the code to not have leftover code from an old integration style)

**Comment by crookedneighbor** [comment] 2020-08-17 22:07
Looks like the merchant account id you are passing when generating the client token may not be correct. Can you verify that?

**Comment by lingwooc** [comment] 2020-08-18 20:28
I've checked it and you are right, I've screwed that up! It works now I've set that to null in magento (use default merchant account). I'm still not sure how it was failing _how_ it did but at least it makes sense _that_ it did.

Thanks for the help. At least there's something online to help the next poor soul who can't perform simple tasks successfully.
