### ISSUE TITLE
Unexpected token o in JSON at position 1 in braintree-web API on request.

### ISSUE THREAD

**Issue by harleenarora** [braintree/braintree-web#436] opened 2019-06-18 12:23 UTC
I have integrate the braintree in my angular 7 application. But I have got the one error. I have search so far but can't get the solution.

_Error::_
```
zone.js:199 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at wk (fb.js:1)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1744)
    at globalZoneAwareCallback
```

**index.html::**
`<script src="https://js.braintreegateway.com/web/3.46.0/js/client.min.js"></script>`

**App.component.ts::**
```
declare var braintree:any;

export class AppComponent implements OnInit {

    ngOnInit(){
        braintree.client.create({
            authorization: 'token'
            }, function (createErr, clientInstance) {
            clientInstance.request({
                endpoint: 'payment_methods/credit_cards',
                method: 'POST',
                data: {
                    creditCard: {
                        number: '4111111111111111',
                        cvv: '123',
                        expirationDate: '12/23'
                    }
                }
                }, function (requestErr, response) {
                    console.log(response)
            });
        });
    }
}
```

Please tell me, how to solve this issue.

**Comment by crookedneighbor** [comment] 2019-06-18 19:02
Looks like you also opened a question on stackoverflow: https://stackoverflow.com/questions/56649040/unexpected-token-o-in-json-at-position-1-in-braintree-web-api-on-request

I just tried this with an Angular 8 example repo: https://github.com/Ismaestro/angular8-example-app

I applied this diff:

```diff
diff --git a/package.json b/package.json
index 7e23c8c..50a3043 100644
--- a/package.json
+++ b/package.json
@@ -57,6 +57,7 @@
     "@ngx-i18nsupport/tooling": "8.0.0",
     "@ngx-translate/i18n-polyfill": "1.0.0",
     "@sentry/browser": "5.4.0",
+    "braintree-web": "^3.46.0",
     "classlist.js": "1.1.20150312",
     "core-js": "3.1.3",
     "express": "4.17.1",
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index f2c91dd..3845017 100755
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -6,6 +6,7 @@ import {UtilsHelperService} from './shared/services/utils-helper.service';
 import {DOCUMENT, isPlatformBrowser} from '@angular/common';
 import {I18n} from '@ngx-translate/i18n-polyfill';
 import {RoutesConfig} from './configs/routes.config';
+import client from 'braintree-web/client';

 declare const Modernizr;

@@ -38,6 +39,24 @@ export class AppComponent implements OnInit {

     this.onEvents();
     this.checkBrowser();
+
+    client.create({
+      authorization: 'sandbox_f252zhq7_hh4cpc39zq4rgjcg'
+    }, function (createErr, clientInstance) {
+      clientInstance.request({
+        endpoint: 'payment_methods/credit_cards',
+        method: 'POST',
+        data: {
+          creditCard: {
+            number: '4111111111111111',
+            cvv: '123',
+            expirationDate: '12/23'
+          }
+        }
+      }, function (requestErr, response) {
+        console.log(response)
+      });
+    });
   }
```

And I see no issues. 

I don't think this is an issue with the SDK, so I'm going to close this issue. Please reach out to our support team with the details of your integration. A reproducible example would be best. https://help.braintreepayments.com/

**Closed by crookedneighbor** 2019-06-18 19:02 UTC
