### ISSUE TITLE
Hosted fields tabbing with arrows on ReactNative iOS keyboard broken in 3.51.0 version

### ISSUE THREAD

**Issue by deviousknight** [braintree/braintree-web#456] opened 2019-09-18 15:54 UTC
### General information

* SDK version: 3.51.0
* Environment: Sandbox/Prod
* React Native iOS WebView

### Issue description

Tabbing with iOS keyboard arrows may lead app to state when cursor will be shifted slightly  like it focused on some hidden field and data in that state can't be edited until you click prev/next arrow again.

![Screen Shot 2019-09-18 at 18 02 11](https://user-images.githubusercontent.com/19371283/65164103-e0766e80-da44-11e9-8cc6-496bcf65b0a3.png)

Meanwhile in v3.52.1 tabbing doesn't work for iOS webview. I created separate issue for it

**Comment by crookedneighbor** [comment] 2019-09-18 16:00
We made some changes in v3.52.1 around the tabbing behavior on devices with software keyboards (see my comment in #457). I'm going to close this particular issue, as it it's using an old version of the SDK.

**Comment by deviousknight** [comment] 2019-09-19 07:39
i made cursor and tabs working in the v3.52.1 like you mention in https://github.com/braintree/braintree-web/issues/457 but this issue is still present in the 3.52.1 so i think its need to be reopened

**Comment by crookedneighbor** [comment] 2019-09-19 13:39
I'm going to re-open it so we can do a little exploration on workarounds, but I believe the underlying cause of this bug is caused by a bug in how iOS Safari treats inputs inside of iframes, so there may not be a real solution here.

Can you provide exact steps to reproduce the behavior? I was not able to reproduce by just tabbing through.

**Comment by deviousknight** [comment] 2019-09-19 15:37
just do some presses on different fields to make them focused and then try to press on iOS arrows keyboard and you should see it.  i could send simple page with sample if it would help

**Comment by crookedneighbor** [comment] 2021-06-15 20:38
After almost 2 years of this, we've finally found a fix! Released in v3.78.2

**Comment by crookedneighbor** [comment] 2021-06-24 16:27
😬  looks like an ios update broke this (again). Either iOS 14.5 or 14.6. Still appears to work in 14.4 and lower. Re-opening and looking for a solution.

**Comment by crookedneighbor** [comment] 2021-07-12 15:15
This is fixed in v3.79.1

The basic problem is that in ios 14.5, Apple released a change where the input arrows would appear if there were inputs in the DOM structure ahead/behind of the current input, but would only actually focus on them if they were visible enough to the browser. We had hidden inputs in the iframe that are not interactable by the user that when they get focus, kick off a process to send a request to capture focus on the following/previous iframe's inputs. 

We've pushed out a fix to mitigate this. However, there's still a minor issue when going backward where it can become impossible to keep tabbing backward. At this point, we're going to close this issue, because the core problem is solved. We have a TODO to explore some alternatives to adjust for the weird back tabbing behavior.

**Closed by crookedneighbor** 2021-07-12 15:15 UTC
