### ISSUE TITLE
Hosted Fields interfering w/ Dashlane CC Autofill 

### ISSUE THREAD

**Issue by eschie** [braintree/braintree-web#298] opened 2017-05-31 00:25 UTC
### General information
Braintree Hosted Fields 3.17 and Below
Sandbox/Production
Chrome 58.0.3029.110 (64-bit) AND Safari 10.1.1
Mac OS X 10.12.5

### Issue description

While using the Dashlane Chrome Extension on a Hosted Fields form, the popup Dashlane Credit Card Modal is positioned incorrectly. This presents a UX problem as the Dashlane cc modal brings focus away from the cc input box until either it is closed or a card is selected.  If the Dashlane cc popup appears outside of the viewport, the user may believe the credit card form to be broken.

I have submitted a bug report to Dashlane in the hopes both teams can work together to resolve.

You can replicate this behavior using Braintree Hosted Field's codepen here: https://codepen.io/braintree/pen/MyzXqG

![dashlanehfbug](https://cloud.githubusercontent.com/assets/1564750/26609979/98bf3ff4-4559-11e7-823e-9a490b6551f6.gif)

**Comment by crookedneighbor** [comment] 2017-06-07 19:10
Can you try reproducing it outside of the codepen iframe? I think the major positioning problem is because of the nested iframes.

When I try hosted fields on a normal page, the positioning is much closer to the hosted fields input.

**Comment by eschie** [comment] 2017-06-08 23:34
Yes, you can reproduce it here.  (using any number of the examples has the dashlane modal pop up on the first example) => https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2

Here's what happens if hosted fields is in a modal:

![dashlanehfbug2](https://cloud.githubusercontent.com/assets/1564750/26610611/74d7e1be-455d-11e7-9e8a-3f741bb1a30c.gif)

**Comment by crookedneighbor** [comment] 2017-06-09 15:14
The positioning of the dashlane interface is likely something Dashlane will have to adjust.

I'm happy to work with a dev from Dashlane if we need to make adjustments on our side, but I have no idea what those adjustments should be. Seems like an incorrect calculation for where the input is inside the iframe.

**Comment by eschie** [comment] 2017-06-21 17:58
I have reached out to Dashlane's support team with ticket reference number #432855.

**Comment by intelliot** [comment] 2017-07-12 18:39
@eschie Thanks for reaching out to them. Please let us know if there's something we can do to help.

**Comment by crookedneighbor** [comment] 2017-07-19 19:34
I don't think there's anything actionable for us to do on this issue, so I'm going to close this. Please let us know if there's anything we can do to help with it and I'll gladly re-open it.

**Closed by crookedneighbor** 2017-07-19 19:34 UTC
