### ISSUE TITLE
es modules

### ISSUE THREAD

**Issue by chase-moskal** [braintree/braintree-web#468] opened 2019-10-17 21:54 UTC
hello friends

my applications are 100% modern es modules

is this library planning to ship es modules so we can use it seamlessly in our modern applications?

ideally the library would meet pika standards so as to be compatible with the modern ecosystem (package.json "module" field, and `"type": "module"`)

**Comment by Lockza** [comment] 2019-10-17 21:54
Feel free to contribute and make those changes

**Comment by crookedneighbor** [comment] 2019-10-17 21:56
I think this is a duplicate of https://github.com/braintree/braintree-web/issues/389

**Comment by crookedneighbor** [comment] 2019-10-17 21:58
Please add your comment to that issue. Closing this one as a duplicate.

**Closed by crookedneighbor** 2019-10-17 21:58 UTC
