### ISSUE TITLE
HOSTED_FIELDS_TIMEOUT in SPA

### ISSUE THREAD

**Issue by okovpashko** [braintree/braintree-web#403] opened 2018-11-28 15:26 UTC
### General information

* SDK version: 3.36.0
* Environment: Production
* Browser and OS: Chrome 70.0.3538.110 (64-bit) on MacOS 10.14.1

### Issue description

Hello.

We use hosted fields and PayPal integrations for a while in our React based SPA.

After upgrading Braintree JS SDK we've noticed a huge amount of `HOSTED_FIELDS_TIMEOUT` errors in our errors tracking system.

I've made some investigation and find the following scenario when this error occurs:
1. User opens payment form popup.
2. Braintree client and hosted fields instance initialization start
3. User clicks on 'PayPal' tab in the payment form **before hosted fields initialization finished**
4. Tab content with credit card form removed from the DOM but `teardown` method of the hosted fields cannot be called because of the hosted fields instance can be accessed only in the callback of `hostedFields.create`.
5. After 60 seconds SDK throws `HOSTED_FIELDS_TIMEOUT` error

Could you please give some advice how to avoid this error?

**Comment by crookedneighbor** [comment] 2018-11-29 16:35
The root cause of this is that there's currently no way to cancel Hosted Fields from loading once it's started. We've gotten a number of reports of people needing this, so I'm thinking we could add something like:

```js
var hostedFieldsCreatePromise = braintree.hostedFields.create(options);

braintree.hostedFields.cancel(hostedFieldsCreatePromise).then(function () {
  // hosted fields setup was succesfully cancelled
});
```

Just need to figure out a few details, like, what's the behavior when `cancel` is called after Hosted Fields is already set up?

**Comment by okovpashko** [comment] 2018-12-05 09:17
Thank you for the response. Looks like the best solution for my case is to ignore `HOSTED_FIELDS_TIMEOUT` error if payment form component is unmounted.
The example you've proposed looks good. The one question I have is how to deal with it if callbacks are used instead of promises.
As for calling `cancel` after Hosted Fields is already set up, I'd propose to return an error (in callback or promise rejection) with a code like `HOSTED_FIELDS_INITIALIZED`.

**Comment by crookedneighbor** [comment] 2018-12-05 19:43
We gave the `cancel` method a go in a spike and decided against it. The API for keeping state about whether or not you could use the `cancel` method turned out to be pretty gnarly, and, as you mentioned, it's impossible to use with the callback API.

The greatest bottleneck in the Hosted Fields creation should be at the client creation level. We've developed a new pattern for instantiating Hosted Fields that allows it to create a client for itself in the background. This dramatically speeds up the time it takes Hosted Fields to set up. Update to v3.39.0 and you can try it out with:

```js
braintree.hostedFields.create({
  authorization: 'client_token_or_tokenization_key',
  // the rest of your hosted fields setup, skipping the client
}, function (err, instance) {
  // set up button
});
```

In addition, if you're using a client token for your authorization, but are not using 3D Secure, you may want to [switch to a tokenization key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3).

This should solve _most_ of the issue you are seeing, the few that might still trickle through from overzealous page navigation can be safely ignored. We're planning to address the few edge cases where you would still see an error like this in the next major version.

**Comment by hollabaq86** [comment] 2019-04-01 15:54
👋 We're going to close this issue, but if you continue to experience problems after switching to the suggested approach above, please let us know and we can re-open this.

**Closed by hollabaq86** 2019-04-01 15:54 UTC
