### ISSUE TITLE
DATA_COLLECTOR_KOUNT_ERROR in versions 3.107.0+

### ISSUE THREAD

**Issue by Tankzor** [braintree/braintree-web#730] opened 2024-10-30 02:40 UTC
### General information

- SDK version: `3.111.0`
- Environment: Sandbox, presumably production but we won't test that!
- Browser and OS: Any (we can repro in many)

### Issue description

We are receiving the following error trying to create a datacollector (`braintree.dataCollector.create`) with `kount: true` after updating `braintree-web` past `3.106.0`. Currently broken in `3.111.0`.

```
code: "DATA_COLLECTOR_KOUNT_ERROR"
details: undefined
message: "can't convert null to object"
name: "BraintreeError"
stack: ""
type: "MERCHANT"
```

Rolling back to `3.106.0` seems to fix the issue, or disabling kount in the call to `braintree.dataCollector.create`. Currently our call looks like this (only passing client):

```
braintree.dataCollector.create({ client: clientInstance, kount: true }, callback);
```

**Comment by Tankzor** [comment] 2024-10-30 22:22
Update: turns out we only had kount enabled in the sandbox and we were using built-in paypal anti-fraud in production, so we've removed the `kount: true` in other environments so this doesn't affect us anymore. I'll leave the issue so you can fix whatever the problem might be, or close it.

**Comment by braintreeps** [comment] 2024-11-04 21:31
Closing as a duplicate of https://github.com/braintree/braintree-web/issues/724

**Closed by braintreeps** 2024-11-04 21:31 UTC
Labels: duplicate
