### ISSUE TITLE
'KeyboardEvent.keyIdentifier' is deprecated

### ISSUE THREAD

**Issue by hypnoboutique** [braintree/braintree-web#198] opened 2016-08-28 13:39 UTC
I'm getting the following warning from hosted-fields-internal.min.js:1 when including braintree-web (braintree-web@3.0.1) into my Aurelia app:

> 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

Just wondering if there was a fix due for this as September is only a few days away (or if it even matters).

**Comment by crookedneighbor** [comment] 2016-08-29 11:27
This is a duplicate of https://github.com/braintree/braintree-web/issues/195 and we've opened an issue in https://github.com/braintree/restricted-input/issues/6 which is the module that actually uses `KeyboardEvent.keyIdentifier`.

The good news is that if you look at the two places we use `keyIdentifier` ([lib/key-cannot-mutate-value.js](https://github.com/braintree/restricted-input/blob/c0379e35568b60ae37f917688254fc36464b676c/lib/key-cannot-mutate-value.js) and [lib/restricted-input.js](https://github.com/braintree/restricted-input/blob/c0379e35568b60ae37f917688254fc36464b676c/lib/restricted-input.js)), there are fallbacks to other keyboard event properties and nothing that would cause the module to start throwing errors.

I've tested it in Chrome Canary and the only difference is that the deprecation messages have been removed 😄

**Closed by crookedneighbor** 2016-08-29 11:27 UTC

**Comment by hypnoboutique** [comment] 2016-08-29 12:06
Ah, ok! Sorry for the dupe..
