### ISSUE TITLE
BraintreeError: Cannot contact the gateway at this time

### ISSUE THREAD

**Issue by jasonfb** [braintree/braintree-web#296] opened 2017-05-17 17:18 UTC
### General information

* SDK version: 3.2.0
* Environment: Sandbox/test environment
* Browser and OS: Poltergeist running phantomjs

### Issue description
We get this error running our specs under Poltergeist and Phantom JS. We are using Phantom JS 2.1.1

I have attempted setting ```--ssl-protocol=tlsv1.2``` to our Phantom JS config but this does not fix the error.

**Comment by crookedneighbor** [comment] 2017-05-17 18:21
First, can you upgrade to the latest version (3.15.0)?

Second, if the issue persists, can you provide a github repo that reproduces the problem with instructions for installing any dependencies and how to run the tests?

**Comment by jasonfb** [comment] 2017-05-17 18:29
Maybe, and yes. I will try to put together a sample app for reproducing

**Comment by reidcooper** [comment] 2017-05-23 14:47
@crookedneighbor 

My coworker is on vacation this week so I took over this ticket at our company. Here (https://github.com/reidcooper/braintree-error-cannot-connect) I have a sample application. 

However, I cannot seem to reproduce the bug at the moment. Will try and determine if it is due a specific commit within our production application.

**Comment by crookedneighbor** [comment] 2017-05-23 16:24
@reidcooper It sounds like there is nothing actionable for us as this moment.

I'm going to close this for now. But as soon as it's reproducible, comment here and I'll re-open it.

**Comment by jasonfb** [comment] 2017-05-27 13:28
@crookedneighbor -- for the posterity of the issue, just waned to report back for others that we confirmed the root cause of this was an (unintentional) double-instantiation of the ```Braintree``` object itself.. When we corrected our code not to double-instantiate, the problem went away. As explained above, symptom did not seem to manifest in Production, only in the phantomjs (with capybara/rspec) test environment. 

Good to close as this was from our own refactor.

**Comment by jasonfb** [comment] 2017-05-27 13:36
cross posted to https://stackoverflow.com/questions/44217489/braintreeerror-cannot-contact-the-gateway-at-this-time-during-system-integrati/44217509#44217509

**Comment by crookedneighbor** [comment] 2017-05-28 02:51
Thanks for the update!

**Comment by carlosds730** [comment] 2018-02-23 18:12
Hello there, since this morning I'm having this same issue with the Sandbox. 

The error is the following

````javascript
{
	code: "CLIENT_GATEWAY_NETWORK",
	details: {
		originalError: "error"
	},
	message: "Cannot contact the gateway at this time.",
	name: "BraintreeError",
	type: "NETWORK"
}
````

**Comment by jasonfb** [comment] 2018-02-23 18:20
did you contact support at support@braintreepayments.com

unless it's on your end, I'd reckon a network error is on their end.

sounds unrelated to code implementation.

**Comment by carlosds730** [comment] 2018-02-23 18:27
Well, the issue is that it works on Firefox, IE and Edge, it only fails on Chrome

**Comment by jasonfb** [comment] 2018-02-23 18:32
huh?

Ah yes sorry didn't read closely.

not sure if it is related but you can see our notes on the fix related to the original issue above

**Comment by carlosds730** [comment] 2018-02-23 18:40
I've read your post on the fix, however, I'm using JS SDK version 3.31, which already has that fix in place. Is this possible that it is related to this issue https://github.com/braintree/braintree-web/issues/343 ?

**Comment by carlosds730** [comment] 2018-02-23 18:50
It now fails on Firefox, Edge and Chrome (all in Windows). I've tested with Firefox and Chrome on Ubuntu and it works fine. What could it be?

**Comment by jasonfb** [comment] 2018-02-23 18:51
it's possible. are you experiencing this in actual Chrome or in chromedriver driving chrome?

If you are seeing this in the spec suite (using chromedriver), be sure to update chromedriver to the latest.

**Comment by carlosds730** [comment] 2018-02-23 18:51
I'm having the problem with real Chrome **Version 64.0.3282.167 (Official Build) (64-bit)**

**Comment by carlosds730** [comment] 2018-02-23 19:13
It only happens in the sandbox. I see no other errors in the sandbox. It appears to be a CONNECTION_CLOSED.

**Comment by crookedneighbor** [comment] 2018-02-23 19:15
@carlosds730 Definitely contact support so we can get more details about it. I'll re-open the issue.

**Comment by carlosds730** [comment] 2018-02-23 19:16
Ok, I'll send them an email, and put a link to this issue

**Comment by carlosds730** [comment] 2018-02-23 21:01
I opened a Support Ticket and somehow it got fixed. I guess you can close the issue. Thanks for everything

**Comment by carlosds730** [comment] 2018-02-23 22:34
It's happening again

**Comment by crookedneighbor** [comment] 2018-02-27 22:51
I checked our ticketing system and it looks like the issue is resolved for you now. Going to close this.

**Closed by crookedneighbor** 2018-02-27 22:51 UTC

**Comment by genisgetman** [comment] 2019-02-11 14:58
I resolved this problem by adding

**Comment by crookedneighbor** [comment] 2019-02-11 15:11
@genisgetman I assume this is a limitation with something in your development environment, and not in production.

**Comment by MatissJanis** [comment] 2019-11-07 09:09
We've been lately receiving quite a lot of these exceptions in our bugnsag account. Not sure how to reproduce.

**Comment by crookedneighbor** [comment] 2019-11-07 15:13
@MatissJanis please reach out to our support team: https://help.braintreepayments.com/

**Comment by thanatos11** [comment] 2020-02-13 13:26
I also have this problem:
JS SDK
Environment: sandbox
Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Error function: Braintree.client.create()
Error Output:
{
name: "BraintreeError"
code: "CLIENT_GATEWAY_NETWORK"
message: "Cannot contact the gateway at this time."
type: "NETWORK"
}

**Comment by GeorgeLinut** [comment] 2020-02-13 13:43
We experience the same problem as @thanatos11.

**Comment by ganedda-softfobia** [comment] 2020-02-13 13:45
We too

**Comment by dmolnarqu** [comment] 2020-02-13 13:46
Must be on their end. It started happening in the middle of testing today.

**Comment by dnwilson** [comment] 2020-02-13 14:05
Just here to say me too 😢 . Glad to know we're all in this together today 💪

**Comment by riccardomessineo** [comment] 2020-02-13 14:13
Not working :(

![image](https://user-images.githubusercontent.com/10194398/74443197-13495500-4e73-11ea-9dca-9c748299c2b0.png)
Why bother having a status page that displays wrong information? I really don't get it. 
And it's not just a Braintree problem, every status page of every online service I've seen 
says it's ok while it isn't!

**Comment by dnwilson** [comment] 2020-02-13 14:17
Looks like it's working again

**Comment by dnwilson** [comment] 2020-02-13 14:26
It started working on my staging but still down on my local env

**Comment by crookedneighbor** [comment] 2020-02-13 14:56
Anyone that is having issues, please contact our support team so we can dig into what is going on. https://help.braintreepayments.com/

**Comment by simeyla** [comment] 2021-03-24 07:00
For anyone getting `CLIENT_GATEWAY_NETWORK` that simply having an HTTP debugging proxy tool (such as Fiddler) open can cause CORS errors.  There are other reasons, but if a customer or tester is getting this error it may be worth asking if they are using such a tool.

I just opened this issue in hopes of further exploration: https://github.com/braintree/braintree-web/issues/562

**Comment by crookedneighbor** [comment] 2021-04-08 16:28
Just to follow up on this, the comment about Fiddler was because @simeyla had custom rules on without realizing it: https://github.com/braintree/braintree-web/issues/562#issuecomment-806357436

**Comment by reyesvicente** [comment] 2021-08-23 06:14
Getting this error now
python sdk v4.12.0
hosted fields v3.80.0

```
{
  "name": "BraintreeError",
  "code": "CLIENT_GATEWAY_NETWORK",
  "message": "Cannot contact the gateway at this time.",
  "type": "NETWORK",
  "details": {
    "originalError": "error"
  }
}
```

**Comment by yongchengchen** [comment] 2021-11-16 04:50
Getting the error today.
hosted fields v3.80.0.  there's one of our customer, keep get the error. first use his home network, then change to  mobile phone hot spot, both got error.
{
  "name": "BraintreeError",
  "code": "CLIENT_GATEWAY_NETWORK",
  "message": "Cannot contact the gateway at this time.",
  "type": "NETWORK",
  "details": {
    "originalError": "error"
  }
}
