### ISSUE TITLE
UnMinified js

### ISSUE THREAD

**Issue by mnoack** [braintree/braintree-web#130] opened 2016-02-11 00:54 UTC
Hi,
Can you include an unminified js in the project.

We run all our files through a minifier (UglifyJS) and bundle them into a single file.

UglifyJS goes extremely slow when trying to minify already minified JS (like dist/braintree.js)

Every other npm/bower library we use provides a non-minified file, which could also be useful for development purposes.

Here is the discussion about this issue: https://github.com/webpack/webpack/issues/615

**Comment by mrak** [comment] 2016-02-11 01:00
This is a duplicate of #1 

> We hope to include unminified source in a future version, but as of now there are no plans to include an unminified version here.

https://js.braintreegateway.com/js/braintree-2.19.0.js

Sorry.

**Closed by mrak** 2016-02-11 01:00 UTC
Labels: duplicate
