### ISSUE TITLE
braintree-web (3.1.0) breaks JHipster production build

### ISSUE THREAD

**Issue by lbehnke** [braintree/braintree-web#210] opened 2016-09-12 09:42 UTC
**Symptom**

After adding braintree-web to a JHipster 3.6.1 project (via bower), the production build no longer works. Compiles, builds, starts w/o errors. Blank screen after hitting main page.

**Reproduction**

Install the latest versions of Oracle Java 8, Git, Node.js, Yeoman, Bower, Gulp and JHipster:
See https://jhipster.github.io/installation/ for details.

Set up a new application from scratch:

    $ mkdir myapp && cd myapp
    $ yo jhipster
    
Confirm defaults.
   
Set up a production database or simply copy DB settings from `dev` profile
to `src/main/resources/config/application-prod.yml`. E.g.

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/myapp;DB_CLOSE_DELAY=-1
        name:
        username: myapp
        password:

Build and start production package:

    $ ./mvnw clean package -B -Pprod -DskipTests=true
    $ java -jar target/myapp-0.0.1-SNAPSHOT.war

Open `http://127.0.0.1:8080` in Browser. You should see the JHipster welcome
page.

Now add the `braintree-web` module (I tested 3.1.0) to the project, build
for production and start server:

    $ bower install braintree-web --save
    $ gulp inject
    $ ./mvnw clean package -B -Pprod -DskipTests=true
    $ java -jar target/myapp-0.0.1-SNAPSHOT.war

You should now see a rather blank screen.
These error messages appear in the console:

* index.js: Uncaught ReferenceError: require is not defined(anonymous function) @ index.js:2
* app.module.js: Uncaught ReferenceError: angular is not defined(anonymous function) @ app.module.js:4(anonymous function) @ app.module.js:23

I was not able to pinpoint the cause (as I am fairly new to the build system and Braintree) but I suspect that the gulp configuration is not compatible with `braintree-web`. As this lib is the only one I encountered problems with, I reported the error here.

**Comment by crookedneighbor** [comment] 2016-09-12 13:27
This is a duplicate of #194 

See my answer here: https://github.com/braintree/braintree-web/issues/194#issuecomment-240422087

In short, the index.js file should not be used with bower. You should instead use the individual files you need. Docs here: https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3#install-with-bower

Since this has come up before, we'll discuss as a team if we should do anything different for our Bower release to make integration with Bower easier. Might be as simple as adding that documentation to the README file of this repo.

**Closed by crookedneighbor** 2016-09-12 13:27 UTC

**Comment by lbehnke** [comment] 2016-09-12 13:50
Thanks for the quick response. It solves my problem.
I'd strongly opt for supporting **gulp-inject** as this is a real timer saver (when it works...).

**Comment by crookedneighbor** [comment] 2016-09-12 14:13
Maybe I'm misunderstanding how gulp-inject works, but I don't see why it wouldn't work as is. For instance, if you were building a hosted fields integration:

```js
var gulp = require('gulp');
var inject = require('gulp-inject');
 
gulp.task('index', function () {
  var target = gulp.src('./src/index.html');
  var sources = gulp.src([
    './path/to/your/apps/files', 
    './path/to/bower_components/braintree-web/client.js',
    './path/to/bower_components/braintree-web/hosted-fields.js',
  ], {read: false});
 
  return target.pipe(inject(sources))
    .pipe(gulp.dest('./src'));
});
```

You wouldn't want to inject all of braintree-web's js files, because that would increase the time it takes your page to load with code that you would never use.

**Comment by lbehnke** [comment] 2016-09-12 14:26
I use gulp-inject only as part of the JHipster workflow.
Which would be something like

    $ bower install braintree-web --save
    $ gulp inject

This works for all my 3rd party dependencies. It would be cool if braintree-web supported this, too.
I created a feature request #211 for this.
