### ISSUE TITLE
`.bt-overlay` not removed on teardown

### ISSUE THREAD

**Issue by schneiderik** [braintree/braintree-web#70] opened 2015-09-18 15:46 UTC
This issue was created in response to @bezhermoso's comment in https://github.com/braintree/braintree-web/issues/29#issuecomment-141204216.

**Comment by schneiderik** [comment] 2015-09-18 15:55
Hi @bezhermoso,

I'm taking a look at the `.bt-overlay` issue you raised in https://github.com/braintree/braintree-web/issues/29#issuecomment-141204216.

I have not been able to reproduce this issue in Chrome (v45.0.2454.85).  Would you be able to provide additional details about the issue?  Specifically:
1. The browser you're seeing the issue on
2. Your `braintree.setup` code
3. Your call to `teardown` as well as its callback that you mentioned you were using
4. The steps you took to arrive at your issue

Thanks!

**Comment by bezhermoso** [comment] 2015-09-18 16:05
Hi @schneiderik 

I just removed my code that removes `.bt-overlay` and tested it again -- it doesn't happen anymore. It was probably something was caused by something else.

**Comment by EvanHahn** [comment] 2015-09-18 16:22
@bezhermoso It sounds like this issue has been solved. Should we close this?

**Comment by bezhermoso** [comment] 2015-09-18 16:27
Yes.

**Comment by EvanHahn** [comment] 2015-09-18 16:33
Sounds good. Let us know if you encounter any other issues!

**Closed by EvanHahn** 2015-09-18 16:33 UTC
