### ISSUE TITLE
Blocked a frame with origin

### ISSUE THREAD

**Issue by Jhonsem** [braintree/braintree-web#278] opened 2017-04-01 02:22 UTC
### General information

* Javasrcipt v3 sdk
* Safari browser

### Issue description

just show in the safari browser,how to deal with it?

Blocked a frame with origin "https://assets.braintreegateway.com" from accessing a frame with origin "https://mysite.com". Protocols ,domains, and ports must match.

**Comment by Jhonsem** [comment] 2017-04-01 02:25
I had setted a Content Security Policy in my site,but it not work

**Comment by intelliot** [comment] 2017-04-05 22:18
@Jhonsem We were not able to reproduce this error with:

- JS SDK version 3.12.0
- Safari Version 10.1 (12603.1.30.0.34) on macOS

Could you provide more details about your setup?

Do you have a staging/demo site where we can see this error occurring?

Thanks!

**Comment by eranCo** [comment] 2017-04-12 14:12
@intelliot, This is happening to me too

- JS SDK version 3.12.1
- Safari 9.1.2 (11601.7.7)

Doesn't happen in other browsers
![braintree safari error](https://cloud.githubusercontent.com/assets/21173652/24961950/119b04da-1fa3-11e7-9c0b-ed385c714fd4.png)

**Comment by intelliot** [comment] 2017-04-12 18:32
@eranCo I wasn't able to reproduce these errors. It looks like something like this could be caused by LastPass. Do you use the LastPass browser extension?

Do these errors present any symptoms or prevent Hosted Fields from working?

Also, do you have a staging site where we can see these errors occur?

**Comment by eranCo** [comment] 2017-04-13 07:22
@intelliot, no, I don't have LastPass installed and we reproduced it on several different machines.

Hosted fields seems to work fine. The errors appear during the create process, but everything continues to work.

Unfortunately, only our stuff can access our staging environment. Sorry.

**Comment by intelliot** [comment] 2017-04-13 21:17
@eranCo Although the errors appear in the console, it sounds like it doesn't affect the site's behavior, so it may be okay to ignore. Does this occur on a production (or public) site?

**Comment by Jhonsem** [comment] 2017-04-14 06:33
@intelliot as you said, it sounds like it doesn't affect the site's behavior,but i can sure it is a bug in WebSDK

**Comment by eranCo** [comment] 2017-04-18 07:38
@intelliot, we didn't deploy it to production yet, but on staging it seems like it's working fine other then the console error. We'll monitor it after deploying to production and keep you updated.
Thanks!

**Comment by crookedneighbor** [comment] 2017-04-18 14:01
This is a known issue with Safari and post message being overzealous with their logging when you are including other iframes on your page (such as with Facebook like button). 

If you want to provide us a staging site that reproduces the error, we're happy to take a look and see if there's anything we can do to avoid the console errors, but since it doesn't prevent braintree-web from working, I'm going to close this for now.

**Closed by crookedneighbor** 2017-04-18 14:01 UTC

**Comment by eranCo** [comment] 2017-05-16 09:00
@crookedneighbor - this behaviour can now be reproduced on our production site. I'll be happy to provide detailed instructions if you're interested

**Comment by crookedneighbor** [comment] 2017-05-16 12:21
@eranCo Feel free to either post the link here with steps to reproduce or email support@braintreepayments.com

**Comment by eranCo** [comment] 2017-06-04 08:06
@crookedneighbor sorry for the late response, I emailed support with steps to reproduce. Thanks.
