### ISSUE TITLE
Safari on iOS brings up numeric keyboard for name field

### ISSUE THREAD

**Issue by davidbarratt** [braintree/braintree-web#541] opened 2020-11-17 17:16 UTC
### General information

* SDK version: 3.65.0
* Environment: Production
* Browser and OS: Safari on iOS

### Issue description
> When trying to add a new credit card, tapping into the name field brings up the numbers keyboard instead of the letters making it impossible to add your name unless you have an autofill option that you can select to populate the field with.

I'm not sure what is causing this problem, but I believe adding the [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) attribute should help resolve the ambiguity that Safari on iOS might be facing.

**Comment by crookedneighbor** [comment] 2020-11-17 17:20
This is a duplicate of #523 and was fixed in v3.66.0

I'll take a look at your PR and see if that's something we want to add or not, but as the underlying issue of displaying the numeric keyboard was already fixed, I'm going to close this issue.

**Closed by crookedneighbor** 2020-11-17 17:20 UTC
