### ISSUE TITLE
Uncaught TypeError: Cannot read property ‘hostedFields’ of undefined

### ISSUE THREAD

**Issue by dyatko** [braintree/braintree-web#391] opened 2018-10-02 14:23 UTC
### General information

* SDK version: 3.36.0
* Environment: Sandbox
* Browser and OS: Chrome Version 69.0.3497.100 (64-bit) on MacOS 10.14

### Issue description

We run e2e tests which get a flaky error.

![image](https://user-images.githubusercontent.com/31615495/46354541-21704a00-c65f-11e8-9c14-ccde45a987cc.png)

**Comment by crookedneighbor** [comment] 2018-10-02 14:31
Can you give more information about your testing setup so we can try to reproduce it?

**Comment by gtroshinnc** [comment] 2018-10-02 14:45
> Can you give more information about your testing setup so we can try to reproduce it?

testcafe framework - 0.22.0

Payment with test Visa or MasterCard. 

Can you please tell me details you need and I will provide?

**Comment by gtroshin** [comment] 2018-10-04 07:09
> We haven't experienced this ourselves in our automated testing. Does this seem to occur in a particular browser? Are there any patterns you can detect at all?


As I already mentioned: Chrome 69.0.3497.100 (64-bit) on MacOS 10.14
But it is also reproducible in Chromium 69.0.3497 with Ubuntu 16.04.5.
Happening when running tests to try payment with Visa, MaserCad / with and without 3dsucure. When auto test finish filling Card Number, Expiration Date and CVV and submit this form by button.

Let me know if you need more details or maybe video?

**Comment by crookedneighbor** [comment] 2018-10-04 15:28
It's very odd, if this was flaky in a particular browser, I'd expect it to be on Internet Explorer, not Chrome.

Under normal circumstances, this should never happen, as the frame needs to report that it's ready before it can be orchestrated and told to initialize. If it can report that it is ready, then it _does_ have the `braintree` object on the window.

I don't suppose you're doing anything with the post message API that might be causing this?

The only other thing I can think of is if somehow it's trying to talk to a Braintree frame that doesn't actually belong with hosted fields. I don't see how that can be, because we assemble the frames like this: https://github.com/braintree/braintree-web/blob/93abd00e108c30af1c289bf891459c2fd513fabd/src/hosted-fields/internal/assemble-iframes.js#L10-L15

So we only add frames that match the href. If they don't match, or throw an error because they're not on the same domain, they don't get added. Even if there are multiple hosted fields integrations on the page, they should all have a unique hash so it should only collect iframes that are part of the same integration.

In any case, we're going to add some logic here: https://github.com/braintree/braintree-web/blob/93abd00e108c30af1c289bf891459c2fd513fabd/src/hosted-fields/internal/index.js#L293-L295

to detect if the braintree object exists on the frame. I don't think that will solve the underlying issue, but I think it will expose it more clearly. (IE, a certain iframe isn't populating or something)

**Comment by gtroshin** [comment] 2018-10-11 08:03
> I don't suppose you're doing anything with the post message API that might be causing this?

I as know we do not. By maybe @dyatko can add something.

**Comment by crookedneighbor** [comment] 2018-10-11 12:03
v3.38.1 adds a try catch around the `initialize` call (https://github.com/braintree/braintree-web/blob/0462655549de073897fa6b28be05c24d3223cf4c/src/hosted-fields/internal/index.js#L317-L319)

So this will either fix the problem, or expose the underlying problem.

3.38.1 also takes care of a possible race condition where it was possible for a frame to not be ready when hosted fields initializes the frame, which _may_ be the cause of the issue.

I'm going to close this issue for now, but if y'all are still seeing problems after updating to 3.38.1, comment here and we'll re-open it.

**Closed by crookedneighbor** 2018-10-11 12:03 UTC
