### ISSUE TITLE
Hosted Fields used together with the data-collector throw an 'Unexpected Token' Exception

### ISSUE THREAD

**Issue by fbrosda** [braintree/braintree-web#428] opened 2019-05-07 16:23 UTC
### General information

* SDK version: 3.44.2 and back at least till 3.34.0
* Environment: Sandbox, production
* Browser and OS: Tested on Chromium 73 on Ubuntu 18.04

### Issue description

There seems to be another problem similar to the one described here: https://github.com/braintree/braintree-web/issues/371.

From what I observed, this might be the same issue as before, therefore the link to the codepen from the old issue is still valid. I tried a few different Versions of the sdk and all seem to be affected by this issue.

I think the actual payment process is not affected by the errors, but it is quite unfortunate, that it is not possible to downgrade to a version, which is not affected by this bug.

**Comment by demerino** [comment] 2019-05-08 22:10
Could you be more specific with the error you're seeing and how it manifests? The old issue appeared to have been resolved so we just want to make sure we fully understand what you're seeing.

**Comment by fbrosda** [comment] 2019-05-09 12:04
Hi,

thanks for the fast reply. What I see in the linked codepen from the old issue are a lot of requests in the network tab which log the `SyntaxError: Unexpected Token...` as soon as I click into any field and start typing.

The exceptions are caught, but I was quite sure, that this behavior just appeared recently
If I'm mistaken and it all works as intended and it's just logging of exceptions, which cannot be avoided, sorry for the unnecessary issue.

**Comment by crookedneighbor** [comment] 2019-05-09 16:01
This looks to me like something that codepen is blocking. The same network error does not manifest on an integration outside of codepen.

**Comment by fbrosda** [comment] 2019-05-09 19:48
Sorry, if the description was not clear enough.

The requests are not blocked and I can reproduce the exact same behavior on a normal webpage. It is about the requests which are send, as soon as any of the fields get focused and I start typing:

Host: https://c.paypal.com/v1/r/d/b/e
Parameter:

```
{"appId":"BRAINTREE_SIGNIN","correlationID":"250f6140c7cca2d0372396769ce4447b","e":"JSON.parse: unexpected character at line 1 column 1 of the JSON data","stack":"Kk%40https%3A%2F%2Fc.paypal.com%2Fda%2Fr%2Ffb.js%3A1%3A49153%0A","rvr":"2.2.1"}
```

I think, that these request are new, but I could be wrong there, but it is definitely not only a codepen issue.

**Comment by crookedneighbor** [comment] 2019-05-09 19:51
Oh, I mistakenly tested on a web app that only had data collector :shame:

I'll re-open this and take a look.

**Comment by crookedneighbor** [comment] 2021-11-10 17:17
Finally found some time to dig into this issue, and after updating to the latest version of the SDK (3.83.0), I was not able to reproduce this issue on the codepen. 

If it's still happening for you, feel free to comment here, but I'm going to close this for now.

**Closed by crookedneighbor** 2021-11-10 17:17 UTC
Labels: bug, Hosted Fields, Data Collector
