### ISSUE TITLE
Paypal Popup Safari

### ISSUE THREAD

**Issue by savroff** [braintree/braintree-web#176] opened 2016-06-30 18:53 UTC
Hi guys, 
when I try to tokenize Paypal, Braintree attempts to open a popup, and all looks good in most of the browsers.
But, we have a problem in Safari, because in settings they have `block popups` option active by default, the problem is people even don't have an idea that Safari blocks popup. 
![safari settings](https://www.dropbox.com/s/j0qbkhd0ip0dcu6/Screenshot%202016-06-30%2021.50.58.png?dl=1)

We just created a note text on overlay, but still, it's not the best way to do this:
![notification](https://www.dropbox.com/s/klefjqwi13bk1aw/Screenshot%202016-06-30%2021.52.01.png?dl=1)

How can we solve this problem?

Version 3-beta

**Comment by mrak** [comment] 2016-07-01 16:00
Browsers will block popups if they are not triggered from a user action.

Are you calling `paypal.tokenize` within the click event handler?

If Safari is blocking _all_ popups no matter their mechanic, then the overlay text you have provided to users is mostly likely your best option.

Is it desktop safari? iOS safari? specific versions? We can try an reproduce this if we have some more information :)

**Comment by savroff** [comment] 2016-07-02 07:36
Hi, 
Desktop Safari (v 9.11)

We use React and do `paypal.tokenize` with `onClick`.

**Comment by mrak** [comment] 2016-07-07 17:13
Thanks, we'll take a look.

**Comment by mrak** [comment] 2016-07-12 17:30
Hi @savroff, we are still unable to reproduce this in Safari 9.1.1 with `Block pop-up windows` enabled.

[Here is a JSFiddle](https://jsfiddle.net/k950doj4/2/) using React.js and its `onClick` functionality to initiate `paypal.tokenize`.

**Comment by crookedneighbor** [comment] 2016-07-19 15:52
@savroff We're still not able to reproduce, so we're going to close this now. Feel free to re-open it if you need further help.

**Comment by savroff** [comment] 2016-07-21 19:34
@crookedneighbor 
@mrak 

It's actually easy to reproduce here:
https://jsfiddle.net/5fL6sbyh/

**Comment by crookedneighbor** [comment] 2016-07-21 20:29
@savroff the problem is that due to the asyncronous nature of the create calls, the browser does not see the tokenize call as a direct effect of the user's click action. I've moved the create logic into the `componentDidMount` function. Now that `paypal.tokenize` is called directly after the click event, it does not get blocked.

(Not a React developer, so forgive me if I'm not following the right conventions here)

```js
var paypal;

class PayPal extends React.Component {
  constructor(props) {
    super(props);
    this.clickHandler = this.clickHandler.bind(this);
  }
  
  componentDidMount() {
    braintree.client.create({
      authorization: 'authorization-token-here'
    }, function(err, client) {
      braintree.paypal.create({
        client: client
      }, function(err, paypalInstance) {
        paypal = paypalInstance;
      })
    })
  }

  clickHandler() {
     paypal.tokenize({
       flow: 'checkout',
       amount: '1.00',
       currency: 'USD'
     }, function () { console.log('Tokenization:', arguments); });
 }

 render() {
   return (
    <div>
      <button onClick = {this.clickHandler}>
            PayPal
      </button>
    </div>
   );
 }
}

ReactDOM.render( < PayPal / > ,
    document.getElementById('container')
);
```

**Closed by crookedneighbor** 2016-07-21 20:29 UTC
Labels: PayPal, v3 beta

**Comment by savroff** [comment] 2016-07-22 17:34
Thanks!
