### ISSUE TITLE
onReady not fired when the container or a parent is hidden

### ISSUE THREAD

**Issue by chambo-e** [braintree/braintree-web#121] opened 2016-01-24 06:21 UTC
Hi,

I am developing an Angular SPA and I noticed that the onReady callback was not called when the container was hidden.

Explaining myself:
I have a registration process in two steps:
- the first dedicated to user informations inputs
- a second to payments methods hidden (with a ng-show) while the first one has not been completed.
During the first step I prefetch a braintree token, to avoid the latency for the second one.

I made a custom test without Angular to confirm that:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>BT test</title>
        <script src="braintree.js"></script>
    </head>
    <body>
        <form>
            <div id="reg-dropin"></div>
            <button type="submit">Hello</button>
        </form>
    </body>
    <script>
        console.log('setup ' + new Date());
        braintree.setup('token', 'dropin', {
            container: 'reg-dropin',
            onReady: function() {
                console.log('ready ' + new Date());
            }
        });
    </script>
</html>
```

Result:
![screenshot from 2016-01-24 07-12-28](https://cloud.githubusercontent.com/assets/2802867/12534809/deac479c-c269-11e5-9c82-6bcfdf3cfe6e.png)

```html
<!DOCTYPE html>
<html>
    <head>
        <title>BT test</title>
        <script src="braintree.js"></script>
    </head>
    <body>
        <form style="display:none;"> <!-- Notice the display here -->
            <div id="reg-dropin"></div> <!-- Act the same if we put the style on the container -->
            <button type="submit">Hello</button>
        </form>
    </body>
    <script>
        console.log('setup ' + new Date());
        braintree.setup('token', 'dropin', {
            container: 'reg-dropin',
            onReady: function() {
                console.log('ready ' + new Date());
            }
        });
    </script>
</html>
```
Result:
![screenshot from 2016-01-24 07-11-52](https://cloud.githubusercontent.com/assets/2802867/12534816/486e7b78-c26a-11e5-8580-6a6324e38f7b.png)

So I'm wondering if this is by design or a bug since the element is correctly in the DOM ? 

I am using the version 2.18 of braintree-web and tested this case on Chrome and Firefox, both have the same result

**Comment by kyledetella** [comment] 2016-01-25 13:38
@chambo-e, the issue you described is the expected behavior. The Drop-in will not report `onReady` until the UI has rendered into a state which the user can interact with it. As such, we wait until the appropriate `transitionEnd` events have fired to call `onReady`. When the DOM containing Drop-in is hidden, the browser will defer running those transitions until it becomes visible.

If keeping the checkout hidden is critical to your experience, I would recommend looking into [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview) since that defers the mechanics of presentation to you.

I hope this helps. I am going to close the issue, but feel free to follow up if you have more questions.

**Closed by kyledetella** 2016-01-25 13:38 UTC

**Comment by mgd722** [comment] 2016-10-11 01:38
@kyledetella but the drop-in should report onReady once the container is rendered/visible, right?  So if you load the drop-in in a hidden state, when it becomes visible it should report?

**Comment by crookedneighbor** [comment] 2016-10-11 15:19
Unfortunately, that's not how the internals of Drop-In are set up. Since we are working on the next version of Drop-In, we won't be changing this behavior (join  [our SDK announcement group](https://groups.google.com/forum/#!forum/braintree-sdk-announce) to be notified when the new version will be released).

In the meantime, you can adjust the opacity of the parent container. For instance, here's a snippet for having drop-in fade in when it's ready.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Drop-In Demo</title>
    <style>
      #parent {
        opacity: 0;
        transition: opacity 2s;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <form id="checkout" method="post" action="/checkout">
        <div id="payment-form"></div>
        <input type="submit" value="Pay $10">
      </form>
    </div>

    <script src="https://js.braintreegateway.com/js/braintree-2.29.0.min.js"></script>
    <script>
      // Put in your own client token or tokenization key here
      var auth = 'sandbox_g42y39zw_348pk9cgf3bgyw2b';
      var container = document.getElementById('container');

      braintree.setup(auth, 'dropin', {
        container: 'payment-form',
        onReady: function () {
          container.style.opacity = 1;
        }
      });
    </script>
    </body>
</html>
```
