### ISSUE TITLE
Paypal missing `close` method

### ISSUE THREAD

**Issue by MatissJanis** [braintree/braintree-web#347] opened 2018-01-16 08:01 UTC
### General information

* SDK version: 3.28.0
* Environment: Production
* Browser and OS: IE 11.0, Windows 7

### Issue description

**My clients are experiencing this, I have failed to reproduce it personally.**

```
TypeError: Die Eigenschaft \"close\" eines undefinierten oder Nullverweises kann nicht abgerufen werden.\n   at o.prototype.close 
(https://js.braintreegateway.com/web/3.28.0/js/paypal.min.js:1:25851)\n   at i.prototype.close 
(https://js.braintreegateway.com/web/3.28.0/js/paypal.min.js:1:20439)\n   at Anonymous function 
(https://js.braintreegateway.com/web/3.28.0/js/paypal.min.js:2:3701)\n   at t.prototype.invoke
```

**Comment by bluk** [comment] 2018-01-17 23:58
We haven't been able to reproduce this issue. Did you recently upgrade to `3.28.0` and encounter this issue?

**Comment by MatissJanis** [comment] 2018-01-18 06:40
Yes, we upgraded from `3.12.*`.

**Comment by crookedneighbor** [comment] 2018-01-18 13:36
Is there a specific action where this occurs? IE, when attempting to tokenize or calling `close` on the object returned from the `tokenize` method?

**Comment by MatissJanis** [comment] 2018-01-18 13:41
That's a very good question. And to be honest - I have no idea. This seems to be happening to some of our customers. None of them have reported a problem, but we're seeing error popping up in bugsnag.

Here's all the information we have:
- Error always happens in IE 11
- Always happens when trying to open up the paypal payment window
- stacktrace (see above for that)

**Comment by crookedneighbor** [comment] 2018-01-19 14:25
@MatissJanis We recently upgraded our browserify dependency. If you revert to v3.27.0, does the issue persist? Wondering if that has something to do with it.

**Comment by MatissJanis** [comment] 2018-01-19 14:27
I just moved braintree from a external dependency to using this NPM module and bundling locally. I'll see if the issue still persists. If it does, I'll try downgrading.

Either way - will let you know of the progress.

**Comment by crookedneighbor** [comment] 2018-01-19 14:28
Moving to npm should also "resolve" the issue, if it is indeed because of browserify, since the version of braintree-web on npm is not browserified. Definitely let us know if that improves matters, will be helpful to know.

**Comment by crookedneighbor** [comment] 2018-01-22 22:41
You could also update to PayPal Checkout, which lets the PayPal Checkout.js JavaScript library handle the UI for rendering the button and opening the popup. http://braintree.github.io/braintree-web/current/PayPalCheckout.html

**Comment by MatissJanis** [comment] 2018-01-23 07:00
Moving to NPM seems to have resolved the issue. We have not received this error since then.

**Comment by MatissJanis** [comment] 2018-01-23 12:19
Just encountered the same problem with braintree being loaded via NPM. Any ideas?

**Comment by crookedneighbor** [comment] 2018-01-23 15:09
Do you have a staging site where we can attempt to reproduce it? Or at least your client side code?

**Comment by MatissJanis** [comment] 2018-01-23 15:34
Sure, here it is: https://webapp.kasko.io/pk_test_2jngq6d7GRmxQ58w0yVKW3PBrJXbEvoM/tp_a8522ba6f816fab7264d8b1a59c07/

It will create test policies. Braintree paypal integration is also in test mode.

**Comment by MatissJanis** [comment] 2018-01-23 15:42
I was given permission to share the paypal frontend integration code: https://gist.github.com/MatissJanis/d1ce27f3157512abebe1beb742c2ca42

**Comment by crookedneighbor** [comment] 2018-01-25 17:16
So far I have not been able to replicate it. Have you had customers reporting issues? If not, my guess is that the error is benign and is not interrupting the flow.

Ultimately, I'd recommend upgrading away from the deprecated component you are using to PayPal Checkout using the checkout.js script. http://braintree.github.io/braintree-web/current/PayPalCheckout.html

**Comment by MatissJanis** [comment] 2018-01-30 08:33
Thanks. Sadly we don't have capacity to do that right now, but I'll push for it.

Currently I've updated to the latest braintree-web version. The error hasn't appeared for a couple of days now. Will let you know if it starts popping up again.

**Comment by crookedneighbor** [comment] 2018-02-05 17:39
I'm going to close this for now, but please comment here if there's more info for us to investigate.

**Comment by crookedneighbor** [comment] 2018-02-15 19:01
We got another report about this, so I'm re-opening it.

**Comment by steve1000** [comment] 2018-02-19 22:04
This happened to me. Not sure if it's the exact same issue but we were getting the `cannot read property 'close' of null`. I noticed on the latest version of Chrome, it was actually the pop-up blocker stopping the window from opening causing it to be null. Hope that helps.

**Comment by crookedneighbor** [comment] 2018-02-21 14:24
@steve1000 That does help a lot. I think I know what's going on now, thanks!

**Comment by crookedneighbor** [comment] 2018-04-05 20:53
I've added some handling around this for v3.32.0. Can y'all update and report back?

**Comment by MatissJanis** [comment] 2018-04-09 06:34
I've updated braintree version. Will let you know if this error pops up again.

**Comment by jackellenberger** [comment] 2018-04-24 14:53
Hey @MatissJanis and @steve1000, thanks again for bringing this to our attention. It's been a couple weeks on the new version, so I'm going to go ahead and close this issue for now. Let us know if you run into it again and we'll reopen it!

**Closed by jackellenberger** 2018-04-24 14:53 UTC
