### ISSUE TITLE
onReady doesnt work on Meteor application

### ISSUE THREAD

**Issue by mladendinev** [braintree/braintree-web#218] opened 2016-09-24 16:55 UTC
Hello,

I've been trying to integrate braintree into my applicaiton, but I'm receiving an error which I can't figure out myself.

Here is code: 

```js
Template.paymentTemplate.onRendered(function(){

      paymentMethod = function (type) {
          console.log('initial');
          var config;
          config = configBrainTree(type);

          braintree.setup(Template.instance().clientToken, "custom", {
             paypal: { container: 'paypal-container', singleUse: true, },
             onError: function(error){
                console.log(error);
              },
            onPaymentMethodReceived: function (response) {
               if(response.type === 'CreditCard' && validCard())
                  var nonce = response.nonce;
                  console.log(response.type);
                  createTransaction(nonce);
              },
            onReady: function(integration){
                console.log(integration);
                Template.instance().currentIntegration.set(integration);
            }
          });
     }
 });
```

```js
Template.paymentTemplate.onCreated(function(){

     var templateClientToken = Template.instance().clientToken;
     parentInstance = this;
     parentInstance.currentIntegration = new ReactiveVar(null);
     parentInstance.setup = new ReactiveVar(null);
});
```

```js
Template.paymentTemplate.events({
    
    "change input[name='payment-method']" (event, template) {
        $("input[name='payment-method']").each(function(){
           if(this.checked) {
              $("#" + this.id +"-container").attr("style", "");
              var setup = paymentMethod(this.value);
              console.log(template.currentIntegration.get())
              if (template.currentIntegration.get()){
                 Template.instance().currentIntegration.teardown(setup);
              }
              else{
                 setup;
              }
          }
          else {
            $("#" + this.id +"-container").attr("style", "display:none");
          }
        });
    },
});
```

The problem is that onReady is always returning me "Uncaught TypeError: Cannot read property 'currentIntegration' of null" which breaks everything else. Any clue how I can solve this?

Thanks

**Comment by crookedneighbor** [comment] 2016-09-26 15:10
Looks to me like the problem is that when you call `Template.instance()`, it is returning null, which looks like it might be a problem with your Meteor setup, not your Braintree code. I'm going to close this now, but if you think it is actually an issue with the Braintree SDK, feel free to re-open it and include a link to a Github repo that can reproduce the issue.

**Closed by crookedneighbor** 2016-09-26 15:10 UTC
