### ISSUE TITLE
onCancelled Method not called for paypal custom integraton. 

### ISSUE THREAD

**Issue by vijaykumar-krishnaswamy** [braintree/braintree-web#90] opened 2015-10-23 17:29 UTC
I also updated the issue 
   https://github.com/braintree/braintree-web/issues/71

I am still having issues with the onCancelled not being called. This is what we are doing.

including the braintree library from:

js.braintreegateway.com/v2/braintree.js

And we are using paypal custom integration as

braintree.setup(clientToken, "paypal", {
container: this.paypalContainerId,
singleUse: false,
onPaymentMethodReceived: function (obj) {
this.setPayPalPaymentInfo(obj);
this.expandPayPal();
}.bind(this),
onUnsupported: function(){
this.setPayPalPaymentInfo(null);
this.collapsePayPal();
}.bind(this),
onCancelled: function(){
this.setPayPalPaymentInfo(null);
this.collapsePayPal();
}.bind(this)
});

I can verify that the onPaymentMethodReceived is being called. But the onCancelled method is not called anymore.

Any help is appreciated. Thanks!.

**Comment by EvanHahn** [comment] 2015-10-23 17:41
You're right! We're working on getting a fix out. This is a duplicate of issue #89—you can keep up with things there.

**Closed by EvanHahn** 2015-10-23 17:41 UTC
Labels: duplicate
