### ISSUE TITLE
Webpack bundling issue

### ISSUE THREAD

**Issue by mmccoy** [braintree/braintree-web#271] opened 2017-03-10 20:07 UTC
### General information

* SDK version: ^3.4.0
* Environment: Both (Webpack bundling issue)
* Browser and OS: OSX, Chrome 56.0.2924.87 (64-bit)

### Issue description

The project is using angular/express for a checkout flow with braintree integration.  Its been working for some time, but a recent 'npm update' seems to have broken webpack bundling.  I'm receiving console messages about require not being defined when webpack is including braintree-web/index.js

```
Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (index.js:39)
    at __webpack_require__ (bootstrap c66214b…:50)
    at Object.<anonymous> (checkout.component.js:4)
    at __webpack_require__ (bootstrap c66214b…:50)
    at Object.<anonymous> (app.js:30)
    at __webpack_require__ (bootstrap c66214b…:50)
    at webpackJsonpCallback (bootstrap c66214b…:21)
    at app.bundle.js:1
```

The line it breaks on is the first require call from braintree-web:
```
var client = require('./client');
```

Here's the client side code where I'm calling braintree-web:

```
const braintree = require('braintree-web');
```

I'm not sure exactly when this stopped working, but I'd appreciate any input that might help me resolve it.

**Comment by crookedneighbor** [comment] 2017-03-10 20:09
Duplicate of https://github.com/braintree/braintree-web/issues/260

If you have `noParse` in your webpack config for braintree-web, remove it. 

I'm going to close this now, but if you're still having issues, re-open.

**Closed by crookedneighbor** 2017-03-10 20:09 UTC
