### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postMessage' of undefined

### ISSUE THREAD

**Issue by gedex** [braintree/braintree-web#182] opened 2016-07-14 07:29 UTC
We got this sporadically. We're using hosted fields integration. The setup looks like following:

~~~js
try {
	braintree.setup( paypalBraintreeData.token, "custom", {
		id: checkoutFormID,
		hostedFields: paypalBraintreeData.hostedFields,
		onReady: onReady,
		onError: onError,
		onPaymentMethodReceived: onPaymentMethodReceived
	} );
} catch (e) {
	onError(e);
}
~~~

Even wrapping the setup doesn't catch the exception, so I thought this happens async. This happens after the setup and `onReady` is not invoked yet. I scanned `braintree-2.26.0.min.js` for any line that has `postMessage` call and one is missing the try-catch block. It's around this:

~~~js
return e===!1?!1:void i.postMessage(e,n)}
~~~

Since this is working intermittently, I try to reproduce it on several client sites and got one that I could reproduce consistently by throttling the internet connection too. Let me know if you want more detail on that as I couldn't share the URL publicly.

**Comment by mrak** [comment] 2016-07-14 16:14
Hi @gedex, thanks for reporting.

Could you contact our support team at support@braintreepayments.com with the steps for reproduction?

**Comment by mrak** [comment] 2016-07-20 23:32
Closing. Reopen if the root cause exists within our SDK.

**Closed by mrak** 2016-07-20 23:32 UTC

**Comment by gedex** [comment] 2016-07-30 08:52
@mrak I'll come up with simplified test case for this. It turned the issue happened sporadically on test site. One possible culprit is on how we setup and tear down the integration multiple times due to the re-rendering, via AJAX, HTML section where the fields are displayed.

**Comment by jamesdixon** [comment] 2016-08-20 02:15
@mrak did you ever get an answer on this? I'm using the Drop-in UI and experiencing this sporadically as well.

**Comment by Enalmada** [comment] 2017-01-26 18:49
We are using the Drop-in UI and also experiencing this sporadically.

```
TypeError: Cannot read property 'postMessage' of undefined
  at e.reply.e.reply(/js/braintree-2.29.0.min.js:4:9545)
  at MessageEvent.<anonymous>(/js/braintree-2.29.0.min.js:5:2128)
  at MessageEvent.r(/js/braintree-2.29.0.min.js:4:29823)
  at p(/js/braintree-2.29.0.min.js:4:10118)
  at h(/js/braintree-2.29.0.min.js:4:9952)
```

**Comment by intelliot** [comment] 2017-01-26 20:01
@Enalmada Can you provide some reproduction steps?

In particular, which browsers (and browser versions) are you seeing this with?

**Comment by Enalmada** [comment] 2017-01-26 21:03
I just see it in logs after I setup sentry.io javascript monitoring but here is everything I can think of:
We are using pjax between pages (doing setup and teardown between ajax page loading).  Seems to be consistent with other reports above.  Sentry says it is usually happening on chrome.  So far seems to always be on device: HTC 2PST2.

![image](https://cloud.githubusercontent.com/assets/1892132/22350009/00dfb770-e3c7-11e6-9697-d2dd2a664f9f.png)

Test server is available: https://webtest.relationup.com/credits

**Comment by Enalmada** [comment] 2017-01-27 23:40
Just fyi this problem can happen on safari ios10 too and look like this...as a google hook for any others that happen to be searching when they experience it themselves.

```
TypeError: null is not an object (evaluating 'i.postMessage')
  at reply(/js/braintree-2.30.0.min.js:4:9545)
  at ? (/js/braintree-2.30.0.min.js:5:2220)
  at r(/js/braintree-2.30.0.min.js:4:29828)
  at p(/js/braintree-2.30.0.min.js:4:10123)
  at h(/js/braintree-2.30.0.min.js:4:9953)
  at this(raven.js:372:34)
```

**Comment by isaachinman** [comment] 2017-03-05 17:32
Was there ever any resolution on this? Still seeing it now.

**Comment by crookedneighbor** [comment] 2017-03-06 02:47
@isaachinman What version of braintree-web are you using?

**Comment by isaachinman** [comment] 2017-03-06 08:45
@crookedneighbor Sorry for not posting that originally:

    "braintree-web": "2.30.0"

**Comment by crookedneighbor** [comment] 2017-03-06 14:14
Version 2.31.0 includes a change to our post message library that may fix this. Please upgrade and report back if you're still having the issue.

**Comment by isaachinman** [comment] 2017-03-06 14:32
@crookedneighbor Is there an accurate list of releases somewhere? I am fine with upgrading to the latest `2.x` version but need to be 100% sure there aren't any breaking changes.

**Comment by crookedneighbor** [comment] 2017-03-06 16:06
@isaachinman Since 2.x only included the built minified code, we no longer push those changes to this Github repo. Instead, we push them to the repo we use to manage bower releases, which does include the changelog. You can find it here: https://github.com/braintree/braintree-web-bower/blob/2.x/CHANGELOG.md 

Can you provide exact steps to reproduce the issue?
