### ISSUE TITLE
Credit card issue on Samsung Galaxy note 2

### ISSUE THREAD

**Issue by clovnrian** [braintree/braintree-web#265] opened 2017-02-21 10:13 UTC
Hi,
our customers have problem with filling credit card number on Samsung Galaxy note 2 in application webview (it use default browser).
They can input only first 4 digits.

We are using version 3.8

**Comment by crookedneighbor** [comment] 2017-02-21 14:45
What Android version is it? 

Could you send us the useragent of the application webview? You can go to http://www.whatsmyua.com/ in the application webview to get the information you need.

**Comment by clovnrian** [comment] 2017-02-22 13:59
Version of android is: 4.4.2. Unfortunately we couldn't sent useragent.

And we found other device. Samsung Galaxy S3 Neo, Android 4.4.2 with google chrome as default browser.

**Comment by crookedneighbor** [comment] 2017-02-22 15:37
Okay, I think I've figured out what's going on. Our input formatter detects if the browser is the native Samsung browser and turns off input formatting if that is the case. It looks like our logic for detecting Samsung browsers only applies to newer Samsung devices. I've opened a PR that should catch these older devices as well.

If you'd like to try it out, I've set up a test site with the new browser detection behavior: https://crookedneighbor.github.io/ri-test/staging

That url should do input formatting when using Google Chrome and not do input formatting if using the native Samsung browser.

You mentioned it also not working in a `Samsung Galaxy S3 Neo, Android 4.4.2` device. Was this also in a webview (which means it would use the native browser), or was it in the Google Chrome browser?

**Comment by clovnrian** [comment] 2017-02-22 16:21
Thank a lot for quick resolution.
Problem in Samsung Galaxy S3 Neo, Android 4.4.2 was also in webview.

**Comment by crookedneighbor** [comment] 2017-02-23 17:10
3.9.0 should fix the issue for the Samsung Galaxy note 2 (input formatting is now automatically turned off for the native browser). It looks like there are still issues with the Samsung Galaxy S3 Neo, both with the native browser and Android Chrome. We'll continue to work on it.

**Comment by clovnrian** [comment] 2017-03-07 09:49
Hi,
we found another device with the same problem.

Samsung Galaxy J3 with default browser. Right now I don't know the android version, but I will try to find out.

**Comment by lilaconlee** [comment] 2017-03-10 15:36
@clovnrian is the Samsung Galaxy J3 broken for you using 3.9.0?

**Comment by clovnrian** [comment] 2017-03-10 16:05
Yes, we are using version 3.9

**Comment by crookedneighbor** [comment] 2017-03-10 16:06
Were you able to get the user agent for that device?

**Comment by clovnrian** [comment] 2017-03-10 16:11
It's the same case as before, user was in our application webview, so the build-in browser was used.  Customer just report the problem to our customer service so we don't know the version of android.

**Comment by skunkworks** [comment] 2017-03-14 23:04
@clovnrian As far as we can tell based on the expected user agent string for the Samsung Galaxy J3, 3.9.0 should fix formatting issues with Samsung Galaxy J3 devices. This has been tested with the following UA string:

`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J320F Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Mobile Safari/537.36`

Please reopen this issue if you receive further reports or have a user agent string.

**Comment by skunkworks** [comment] 2017-03-15 17:56
Reopening to fix issues with Samsung Galaxy S3 Neo

**Comment by crookedneighbor** [comment] 2017-03-28 18:14
Back on Feb 23rd, I was able to reproduce the issue with the Samsung Neo device. Today, using the same device and v3.11.1, I am unable to reproduce the issue. 

@clovnrian Are you still having issues with the neo after updating to v3.11.1?

**Comment by intelliot** [comment] 2017-04-05 22:20
@clovnrian We were unable to reproduce this issue. If you can provide steps that reliably cause the problem, please let us know!

Closing for now.

**Closed by intelliot** 2017-04-05 22:20 UTC
