### ISSUE TITLE
Missing typescript types in @types/braintree-web

### ISSUE THREAD

**Issue by paales** [braintree/braintree-web#552] opened 2021-01-21 11:58 UTC
### General information

* SDK version: 3.69
* Environment:-
* Browser and OS -

### Issue description

There are quite some typescript definitions missing as mentioned here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49658#issuecomment-729727556

**Comment by crookedneighbor** [comment] 2021-01-21 14:33
Closed as a duplicate of https://github.com/braintree/braintree-web/issues/429

tl;dnr we don't maintain those type definitions, but the next major version of this sdk is being written in Typescript.

**Closed by crookedneighbor** 2021-01-21 14:33 UTC

**Comment by paales** [comment] 2021-01-21 14:42
Ahh cool! Is the new version coming soonish?

**Comment by crookedneighbor** [comment] 2021-01-21 15:11
We've finished converting the underlying open source modules to typescript and have started work on the SDK proper, but no solid ETA yet.
