### ISSUE TITLE
Braintree Paypal issues on IE 11 

### ISSUE THREAD

**Issue by laxman4434** [braintree/braintree-web#166] opened 2016-05-27 04:54 UTC
Hi,
I have created a test project in ASP.NET Webforms using the example given in
https://github.com/braintree/braintree_aspnet_example

I am using all the latest versions of Braintree SDK's(2.60) and latest Js Library (2.24.1)

I have created a sandbox account in braintree and used all the required keys.

Everything works fine in all browsers except IE.

When i click the paypal button on IE, Paypal iframe opens up and shows a blank page.

![image 3](https://cloud.githubusercontent.com/assets/7378501/15597836/95951808-2417-11e6-81a1-ffea1da33a76.png)

When I opened IE developer tools, I can see that the "Access is denied" for the following files.

1) inline-frame.html
2) modal-frame.html

![image 2](https://cloud.githubusercontent.com/assets/7378501/15597865/d6e0d8ec-2417-11e6-9826-338d71891b3f.png)

Also I opened the following link 
https://developers.braintreepayments.com/start/hello-client/javascript/v2 in IE11 and tried to test the demo example. On clicking the paypal button following error was shown

![image4](https://cloud.githubusercontent.com/assets/7378501/15598044/c46a6e4c-2419-11e6-8f48-ce866aedf3b3.png)

On all the other browsers it worked properly.

Any help would be Appreciated.

Thanks,
Laxman

**Comment by mrak** [comment] 2016-05-27 17:43
We are unable to reproduce the issue with IE11 at https://developers.braintreepayments.com/start/hello-client/javascript/v2

![screen shot 2016-05-27 at 10 26 13](https://cloud.githubusercontent.com/assets/491140/15615882/912204ce-23f5-11e6-932d-ad1444a64cd2.png)

It's possible that this only affects specific builds of IE11. Do you mind telling us the exact browser version you are able to reproduce this in?

**Comment by laxman4434** [comment] 2016-05-29 23:31
Thanks for your reply. I am using the following version
![image1](https://cloud.githubusercontent.com/assets/7378501/15636604/549c61f2-2648-11e6-8f2e-20d3e37a368b.png)

Also i have downloaded the sample ASP.NEt project from
https://github.com/braintree/braintree_aspnet_example and tried with my sandbox keys.

It worked in every browser except IE.

Is there anything that I am doing wrong

**Comment by mrak** [comment] 2016-05-31 20:27
We are still unable to reproduce in the IE11 version in your screenshot :(

Do you have any IE extensions installed or Internet Zones in use on your system?

**Comment by laxman4434** [comment] 2016-06-06 07:18
There are no extensions installed on my system. IE is configured to some proxy settings.

**Comment by intelliot** [comment] 2016-06-10 18:53
Hi @laxman4434 -

When you say IE is configured to some proxy settings, which proxy settings are those?

**Comment by crookedneighbor** [comment] 2016-07-07 19:47
@laxman4434 We're happy to keep troubleshooting this if you provide us with the proxy settings so we can attempt to reproduce. Feel free to re-open this issue.

**Comment by zlristovski** [comment] 2016-08-12 11:00
Hi,

Also and I have the same issue, In all web browsers is all good, except in IE 11.

When I click the PayPal button on IE, PayPal page opens up and shows a blank page.

**Comment by zlristovski** [comment] 2016-08-12 11:19
Hi,

I found a solution,, add the following link: https://checkout.paypal.com in Security Sites and the pop-up will open in IE 11

**Comment by laxman4434** [comment] 2016-08-15 06:21
Hi,

I have squid proxy settings.

I have added the link [https://checkout.paypal.com](https://checkout.paypal.com) in Trusted sites under Security settings in Internet Explorer options, as zlristovski suggested and it worked for me.

But how can we tell all the normal users to add these settings while using our website on IE.

**Comment by skunkworks** [comment] 2016-08-16 18:06
Hi,

We have reproduced this issue and will be investigating further.

**Comment by EvanHahn** [comment] 2016-08-24 20:31
@laxman4434 Could we trouble you to reset your IE security settings and seeing if the problem persists? We think it might be related to some custom security rules but aren't sure which ones.

**Comment by Tyrdall** [comment] 2016-08-29 12:21
We also faced this issue on some user's phones. After disabling the new vault flow (Settings -> Processing -> PayPal), users were able to log in and proceed with the checkout.

**Comment by crookedneighbor** [comment] 2016-08-29 13:56
@Tyrdall Do you have any information on what phone models (and browser) were having this issue?

**Comment by Tyrdall** [comment] 2016-08-31 05:48
@crookedneighbor Unfortunately not. I will try to contact a relevant user.

**Comment by Tyrdall** [comment] 2016-08-31 07:42
@crookedneighbor iOS + Safari.

**Comment by mrak** [comment] 2016-09-01 18:55
For those of you experiencing this problem, what version of our SDK are you using, and have you tried updating to the latest? As of this writing, `2.28.0` is the latest version for our 2.x series.

**Comment by visormatt** [comment] 2016-09-06 17:28
This issue exists in `2.27.0`

**Comment by EvanHahn** [comment] 2016-09-06 20:53
@visormatt @tyrdall Could you try updating to the latest v2 version, `2.28.0`?

**Comment by Tyrdall** [comment] 2016-09-06 20:57
@EvanHahn I already did, but I also disabled the new vault flow.

**Comment by intelliot** [comment] 2016-09-06 21:12
@Tyrdall If this issue occurs in iOS + Safari, would you mind creating a new issue for us to track it? We're scoping this issue (#166) to the original post about IE11.

Please include any additional details you have. Anything is helpful.

**Comment by Tyrdall** [comment] 2016-09-06 21:45
@intelliot Sure.

**Comment by visormatt** [comment] 2016-09-06 23:30
@EvanHahn @intelliot 

I've updated our implementation to use `2.28.0` and do still see the issue. That being said, I do think there is something `timing` related in play with this issue. What I am seeing is as follows:

* initial authorization succeeds, but our UI allows for saved PayPal nonce or the ability to `edit` and essentially re-trigger the account selection. 
* it's when the user tries to `edit` that the authorization screen goes white
* now... If I wait (we've tested 2 minutes) before hitting the `edit` link, it will work. 

-- When it fails, very briefly, the auth window will show the PayPal loader

I can create a video to demo this out if that would be helpful, but let me know who to share within the **PayPal Organization** as the I'm running through these on a staging environment.

**Comment by EvanHahn** [comment] 2016-09-09 19:47
@visormatt Could you take the screencast and email it to support@braintreepayments.com? If possible, could you make sure any devtools console is open so that we can see errors? We'll take a look from there.

**Comment by visormatt** [comment] 2016-09-12 21:39
@EvanHahn another team member @matthewhaguemh has sent an email with two videos attached

**Comment by laxman4434** [comment] 2016-10-11 01:00
Hi @EvanHahn ,

Sorry for the late reply.

I did reset all my IE settings and tried. But the problem still persists.

**Comment by mabergh** [comment] 2016-12-02 05:43
Did this get anywhere ? Find a fix ?

**Comment by EvanHahn** [comment] 2016-12-02 18:17
We are still unable to reproduce this. We'd really appreciate it if someone can give us any of the following:

- Reliable reproduction steps. Ideally, these steps would work in one of [Microsoft's official IE virtual machines](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
- JavaScript errors from the developer console
- Any settings you or your corporate network has changed in Internet Explorer
- Which version of Braintree.js you're using

We believe that this happens when trying to checkout in a corporate-managed Internet Explorer setup. Some people have had success when adding `*.paypal.com` as a [Trusted Site](https://answers.microsoft.com/en-us/ie/forum/ie9-windows_7/how-do-i-add-a-site-to-my-trusted-sites-list/98cc77c8-b364-e011-8dfc-68b599b31bf5) in their Internet Explorer settings.

Sorry we don't have a better answer—please send us steps to reproduce this problem!

**Comment by visormatt** [comment] 2016-12-02 19:09
@mabergh and @EvanHahn we've abstracted and reworked our Redux implementation which seems to have fixed our IE issue around popup blockers 👍. 

However, I can't say with certainty whether or not the timing issue noted above is relevant. If it was purely an issue of an indirect (non-touch event / callback) method being blocked, I would think regardless of 2 seconds or 2 minutes it would still block the popup which was not what we were seeing.

**Comment by eschie** [comment] 2017-01-20 02:35
@EvanHahn We are also having this issue the FIRST time PayPal popup window executes on IE 11.  It looks like the preflight CORS request is aborted, causing the tokenization to fail.  On subsequent requests, the popup appears no problem.

**Comment by intelliot** [comment] 2017-01-23 18:51
@eschie This sounds like a bug that we've observed in IE 11 and Microsoft Edge. In these browsers, we will occasionally receive HTTP 408 (Request timeout) responses.

Modern browsers use something called TCP preconnect to improve performance. This means the browser will often open a TCP connection with Braintree servers from your site before the user has requested it.

Because we have a timeout on our servers to avoid keeping open stale connections, these preconnections are often closed before the client actually needs to use them. In most browsers, they will simply reopen a new connection. Edge and IE11 have a bug where they try to reuse the already-closed connection. Because this connection has already been closed, the browser reports the HTTP 408 request timeout error.

We have reached out to Microsoft about this issue, but until it is addressed, you may try the following workaround: "use" and correctly close the unhealthy pre-connect, causing subsequent requests to open a new connection. For example:

```
braintree.setup(/* … */, {
  // … 
  onReady: function () {
    if (isInternetExplorer || isMicrosoftEdge) {
      $.get('https://api.braintreegateway.com', $.noop);
    }
  }
});
```

(This example uses jQuery and omits browser detecting code.)

The `get` request discards any response, since its only purpose is to reset the connection to a healthy state. This worked for us in our testing, but it is definitely a workaround. If you implement this, let us know if you see a drop in the number of failures you see.

Thanks!

**Comment by mabergh** [comment] 2017-01-24 03:16
Thank you for working on this. I appreciate the effort

**Comment by eschie** [comment] 2017-01-25 00:47
@intelliot Aside from the following 3 console errors in IE11:

**Comment by danmbuen** [comment] 2017-03-09 02:23
Still having issue with this. I have done the ff as mentioned above:
1. added *.paypal.com and https://checkout.paypal.com to trusted sites
2. enabled data sources across domains in internet, local intranet, and trusted sites
3. 2-minute waiting time 

the mock sandbox purchase flow window opens but when i clicked 'Proceed with Sandbox Purchase' i would get this error:

![error_66a](https://cloud.githubusercontent.com/assets/5841965/23733064/c1e96352-04b1-11e7-9462-a107f8b121c0.png)

 i got this console info >> "The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337"

settings: IE 11.0.9600.18426, braintree web sdk 3.9.0, 
code:
		braintree.client.create({
                        authorization: '@ViewBag.AuthToken'
                    }, function (clientErr, clientInstance) {
                        braintree.paypal.create({
                            client: clientInstance
                        }, function (paypalErr, paypalInstance) {
                            $('.paypal-button').click(function () {
                                $(".paypal-button").prop('disabled', true);
                                paypalInstance.tokenize({
                                    flow: 'checkout',
                                    amount: amount,
                                    currency: '@System.Configuration.ConfigurationManager.AppSettings["pg:Cur"]',
                                }, function (tokenizeErr, payload) {
                                    if (tokenizeErr) {
                                        $(".paypal-button").prop('disabled', false);
                                    } else {
                                       /*some ajax call*/
                                    }
                                });
                            });
                        });
                    });

it works in chrome and opera..

**Comment by skunkworks** [comment] 2017-03-22 23:15
@danmbuen Can you inspect the page elements and find the "dispatch frame" `iframe` element? It should look something like this:

![screen shot 2017-03-22 at 4 13 04 pm](https://cloud.githubusercontent.com/assets/563375/24224799/796d8900-0f1a-11e7-9832-971f32688f6a.png)

I think there might be something that is blocking the content of this iframe, which is used to communicate between the main window and the popup. A bit of casual Googling brought up some results about an [IE11 bug that blocks the loading of some iframes](https://social.technet.microsoft.com/Forums/en-US/6287fa2f-8843-431d-a6fc-342c34f2d96a/iframe-not-loading-after-installing-update-kb3154070?forum=ieitprocurrentver).

If you can confirm that the iframe content is not loading, can you try updating IE11 with [this KB update](https://support.microsoft.com/en-us/kb/3176757) to see if this fixes the issue?

**Comment by skunkworks** [comment] 2017-04-03 21:19
Closing this issue for now -- please let us know if the KB patch update fixes this behavior.

**Closed by skunkworks** 2017-04-03 21:19 UTC
Labels: PayPal

**Comment by svenbluege** [comment] 2018-04-11 07:57
Right now I encounter that issue as well. Both on our site and on the Braintree doc site https://developers.braintreepayments.com/start/hello-client/javascript/v2

![image](https://user-images.githubusercontent.com/3834825/38603356-b04b2ebe-3d6d-11e8-913e-8537f9069e3c.png)

The difference between working and not working seems to be the domain assignment of the windows user. There must be some policy restrictions in place which cause the popup to be a full window instead of a real popup. I guess the JavaScript from the initiating page loses connection to the popup and it stays empty. So far I was not able to spot the configuration which makes a difference here. 

Any help is welcome.

IE version: 11.192.16299
Edge version: 41.16299.15.0

**Comment by crookedneighbor** [comment] 2018-04-11 12:13
v2 is no longer receiving updates and bug fixes. Can you try upgrading to v3 of the SDK? https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3

The UI is now governed by [PayPal's checkout.js script](https://github.com/paypal/paypal-checkout) and should mitigate issues like this.

**Comment by svenbluege** [comment] 2018-04-11 13:07
![image](https://user-images.githubusercontent.com/3834825/38618472-0da60724-3d9a-11e8-882c-4244aac3315f.png)

Seems like v3 can handle the IE intranet mode... whatever this is :)

**Comment by crookedneighbor** [comment] 2018-04-11 13:46
https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md

**Comment by svenbluege** [comment] 2018-04-11 13:50
Thanks a lot!
